// The English message catalogue (B10): every UI string lives here, so the UI can
// be translated later. No translations or RTL UI mirroring in the MVP.

const fileName = (path: string) => path.split('/').pop() ?? path

export const en = {
  library: {
    emptyTitle: 'Your library is empty',
    emptyBody: 'Drop EPUB files here, or open one from your computer.',
    openBook: 'Open a book…',
    open: 'Open…',
    note: 'Books are copied into your library and stay on this device.',
    title: 'Library',
    count: (n: number) => `${n} ${n === 1 ? 'book' : 'books'}`,
    unknownAuthor: 'Unknown author',
    damaged: (n: number) => `${n} damaged`,
    new: 'New',
    finished: 'Finished',
    percent: (fraction: number) => `${Math.round(fraction * 100)}%`,
    search: 'Search library',
    searchPlaceholder: 'Search title or author',
    sortBy: (label: string) => `Sort by: ${label}`,
    sorts: { recent: 'Recent', title: 'Title', author: 'Author' },
    // 1.1 list view (approved 2026-10-01)
    view: 'View',
    viewGrid: 'Covers',
    viewList: 'List',
    neverOpened: '—',
    continueReading: 'Continue reading',
    allBooks: 'All books',
    resume: 'Resume reading',
    itemMenu: (title: string) => `More for “${title}”`,
    info: 'Book info',
    showFile: 'Show in Finder',
    remove: 'Remove',
    removed: (title: string) => `Removed “${title}”`,
    restore: (title: string) => `Restore “${title}”`,
    noMatches: (q: string) => `No books match “${q}”`,
    // E3; Screen 12
    damagedTitle: 'Part of this book couldn’t be opened',
    damagedBody: (n: number, total: number) =>
      `${total ? `${n} of ${total}` : n} ${(total || n) === 1 ? 'chapter is' : 'chapters are'} damaged. You can read the rest; damaged chapters are marked in Contents so nothing looks silently missing.`,
    damagedFile: (title: string, size: string) => `${title} · ${size}`,
    readAnyway: 'Read anyway',
    showFileShort: 'Show file',
    clear: 'Clear',
    // D7-WebKit (provisional: no screen shows it)
    webkitTitle: 'Books need a newer Safari',
    webkitBody:
      'Linen reads books with the Mac’s own web engine, which comes with Safari. This Mac has an older version than Linen needs: Safari 16.4 or later. Update it in Software Update, then open the book again. Your library and notes are safe.',
    webkitUpdate: 'Open Software Update',
    webkitClose: 'Not now',
  },
  // Settings window (G2, PROVISIONAL; Screen 11 for Extensions)
  prefs: {
    title: 'Settings',
    sections: {
      general: 'General',
      reading: 'Reading',
      library: 'Library',
      extensions: 'Extensions',
      shortcuts: 'Shortcuts',
      about: 'About',
    },
    theme: 'Theme',
    atLaunch: 'When Linen opens',
    atLaunchLibrary: 'Show the library',
    atLaunchBook: 'Reopen the last book',
    textSize: 'Text size',
    lineSpacing: 'Line spacing',
    // 1.1 (approved 2026-10-01)
    font: 'Font',
    pageWidth: 'Page width',
    publisherStyles: 'Publisher styles',
    publisherFull: 'Full',
    publisherBalanced: 'Balanced',
    publisherOff: 'Off',
    publisherHelp:
      'Balanced keeps a book’s design but gives you its line spacing and alignment. Full keeps all of it; Off shows plain text. One book can be simplified from its ⋯ menu.',
    crossfade: 'Page-turn crossfade',
    crossfadeHelp: 'Pages fade into each other over 120 ms instead of changing at once.',
    announcements: 'Announce page turns',
    announcementsHelp: 'Screen readers hear “Page N” after each turn.',
    folder: 'Library folder',
    folderHelp:
      'Your books, covers, highlights and notes are all in this folder. Back it up to keep them; Time Machine does.',
    showFolder: 'Show in Finder',
    exportAll: 'Export all highlights and notes…',
    exportHelp: 'One W3C Web Annotation file per book, which other apps can read.',
    exported: (n: number) => `Exported ${n} ${n === 1 ? 'book' : 'books'}`,
    nothingToExport: 'There are no highlights to export.',
    uninstall:
      'Removing Linen from Applications leaves this folder in place. Delete it too to remove your library.',
    extensionsIntro:
      'Extensions add actions, panels, themes and exporters in fixed places. They can’t change how pages look, and they can’t read your books or notes unless you allow it.',
    extensionsNone: 'Extensions arrive in a later version.',
    singleKeys: 'Single-key shortcuts',
    singleKeysHelp:
      'Keys such as [ ] H and N work while the text has focus. They switch off by themselves while a screen reader runs.',
    showShortcuts: 'Show all shortcuts',
    version: (v: string) => `Version ${v}`,
    aboutLine: 'A quiet EPUB reader. Your books stay on this device.',
    fonts: 'Literata and OpenDyslexic are licensed under the SIL Open Font License.',
    // D1 (approved 2026-09-26)
    privacy:
      'Linen sends nothing anywhere. If something goes wrong, the details are written to a crash log on this Mac, which you can attach to an email if you choose.',
    showCrashLog: 'Show crash log',
  },
  // Extensions (Phase 7; Screens 11, 12; G1, G7 PROVISIONAL)
  extensions: {
    stopped: (name: string) => `${name} stopped responding`,
    restart: 'Restart',
    notResponding: 'Not responding',
    restartNamed: (name: string) => `Restart ${name}`,
    manage: 'Manage extensions…',
    more: 'More actions from extensions',
    via: (name: string) => `via ${name} extension`,
    exported: 'Exported',
    exportFailed: (name: string) => `${name} couldn’t export`,
  },
  // Settings › Extensions (Screen 11) and the install sheet (G1, PROVISIONAL)
  extSettings: {
    install: 'Install from file…',
    builtin: 'Built-in',
    themePack: 'Theme pack',
    off: 'Off',
    canAccess: 'Can access',
    adds: 'Adds',
    can: 'Can',
    nothing: 'Nothing — themes contain no code',
    noAccess: 'Nothing beyond its own storage',
    enabled: (name: string) => `${name} on`,
    failures: (n: number) =>
      `Stopped responding ${n === 1 ? 'once' : n === 2 ? 'twice' : `${n} times`} recently and was restarted. Reading wasn’t affected.`,
    suspended:
      'Stopped responding three times in ten minutes and was paused. Reading wasn’t affected.',
    restart: 'Restart',
    disable: 'Disable',
    incompatible: (why: string) => `Turned off: ${why}.`,
    remove: 'Remove…',
    pin: 'Show its commands in the ⋯ menu',
    restartWithout: 'Restart without extensions',
    shiftHint: 'Also available by holding ⇧ while Linen opens.',
    safeMode: 'Linen started without extensions. They come back the next time it opens.',
    // G1
    installTitle: (name: string) => `Install “${name}”?`,
    updateTitle: (name: string, version: string) => `“${name}” ${version} asks for more`,
    notVerified: 'Not verified by Linen. Install extensions only from people you trust.',
    newAccess: 'New access',
    cancel: 'Cancel',
    installButton: 'Install',
    update: 'Update',
    keepCurrent: 'Keep current version',
    cantInstall: (name: string) => `“${name}” can’t be installed`,
    close: 'Close',
    installed: (name: string) => `“${name}” is installed`,
    removeTitle: (name: string) => `Remove “${name}”?`,
    removeBody:
      'Also delete what it saved? If you keep it, it comes back if you install the extension again.',
    keepData: 'Keep its data',
    deleteData: 'Delete its data',
  },
  // Book info (E10; G3, PROVISIONAL)
  info: {
    label: 'Book info',
    done: 'Done',
    by: 'By',
    publisher: 'Publisher',
    published: 'Published',
    language: 'Language',
    identifier: 'Identifier',
    added: 'Added',
    fileSize: 'File size',
    layout: 'Layout',
    fixed: 'Fixed pages',
    reflowable: 'Reflowable',
    accessibility: 'Accessibility',
    noAccessibility: 'The book gives no accessibility information.',
    description: 'Description',
  },
  // D6: a quiet line; it never interrupts reading
  update: {
    ready: (version: string) => `Update ready · Linen ${version}`,
    restart: 'Restart',
    // Item 32: this install can't replace itself (standard account, disk image).
    available: (version: string) => `Linen ${version} is available`,
    download: 'Download',
  },
  // Import outcomes: wording PROVISIONAL until the G4 designs exist.
  import: {
    addedDamaged: (title: string, n: number) =>
      `“${title}” was added · ${n} damaged ${n === 1 ? 'chapter' : 'chapters'}`,
    alreadyInLibrary: (path: string) => `“${fileName(path)}” is already in your library`,
    replaced: (title: string) => `“${title}” was updated from a newer file`,
    drm: (path: string) => `“${fileName(path)}” is protected by DRM and can’t be opened in Linen`,
    hostile: (path: string) => `“${fileName(path)}” couldn’t be opened safely and wasn’t added`,
    rejected: (path: string, reason: string) =>
      `“${fileName(path)}” couldn’t be opened · ${reason}`,
    fileFilter: 'EPUB',
  },
  reader: {
    // C5 (1.1, approved 2026-10-01)
    simplified: 'This book’s styles are simplified',
    unsimplified: 'This book’s own styles are back',
    undo: 'Undo',
    library: 'Library',
    more: 'More',
    caretOn: 'Caret browsing on. Arrow keys move the caret; Shift and arrows select.',
    caretOff: 'Caret browsing off',
    contents: 'Contents',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    minutesLeft: (n: number) => `${n} min left in chapter`,
    resumedIn: (chapter: string) => `Resumed in ${chapter}`,
    resumed: 'Resumed where you left off',
    goToBeginning: 'Go to beginning',
    backToPage: (page: string) => `Back to page ${page}`,
    back: 'Back',
    pageAnnouncement: (page: number) => `Page ${page}`,
    pageAnnouncementApprox: (page: number) => `About page ${page}`,
    /** An estimated page number (L16), e.g. in “Back to page ≈312”. */
    approxPage: (page: number) => `≈${page}`,
    /** G8: fixed-layout books show their real pages, exactly. */
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `Pages ${pages[0]}–${pages[pages.length - 1]} of ${total}`
        : `Page ${pages[0]} of ${total}`,
    zoomLevel: (zoom: number) => `${Math.round(zoom * 100)}%`,
    zoomFit: 'Fit',
    /** G8: shown only when opening takes over 500 ms. */
    opening: (title: string) => `Opening “${title}”…`,
  },
  search: {
    label: 'Search in book',
    placeholder: 'Search in book',
    clear: 'Clear search',
    count: (n: number, chapters: number) =>
      `${n} ${n === 1 ? 'result' : 'results'} in ${chapters} ${chapters === 1 ? 'chapter' : 'chapters'}`,
    soFar: 'so far',
    searching: (n: number, of: number) => `Searching ${n} of ${of} chapters`,
    showAll: (n: number) => `Show all ${n}`,
    none: (q: string) => `No results for “${q}”`,
    // B6 (1.1, approved 2026-10-01)
    options: 'Search options',
    wholeWords: 'Whole words',
    regex: 'Regular expression',
    invalid: 'This regular expression isn’t valid.',
    next: 'next',
    previous: 'previous',
    back: 'back to your page',
    result: (i: number, n: number, chapter: string) =>
      [`Result ${i} of ${n}`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: 'Navigator',
    tabs: 'Navigator sections',
    search: 'Search',
    notes: 'Notes',
    more: 'More',
    close: 'Close navigator',
    contents: 'Contents',
    loading: 'Reading the contents…',
    generated: 'Generated from headings',
    youAreHere: 'You are here',
    damaged: 'Damaged',
  },
  aa: {
    label: 'Reading settings',
    button: 'Reading settings',
    textSize: 'Text size',
    sizeScope: (px: number) => `${px} px · All books`,
    px: (px: number) => `${px} pixels`,
    theme: 'Theme',
    paper: 'Paper',
    sepia: 'Sepia',
    night: 'Night',
    auto: 'Auto',
    lineSpacing: 'Line spacing',
    compact: 'Compact',
    normal: 'Normal',
    loose: 'Loose',
    layout: 'Layout',
    pages: 'Pages',
    scroll: 'Scroll',
    allBooks: 'All books',
    thisBook: 'This book',
    moreSettings: 'More in Settings…',
    anywhere: '⌘+ ⌘− work anywhere',
    // G12 (PROVISIONAL)
    codeHint: 'Much of this book is code or tables. Scroll may read better.',
    fixedLayout:
      'This book has fixed pages, so its text size and spacing can’t change. ⌘+ and ⌘− zoom the page.',
    // 1.1 (approved 2026-10-01)
    font: 'Font',
    fontBook: 'Book',
    fontLiterata: 'Literata',
    fontSans: 'Sans',
    fontDyslexic: 'Dyslexic',
    fontDyslexicLong: 'OpenDyslexic',
    width: 'Page width',
    narrow: 'Narrow',
    wide: 'Wide',
  },
  annotations: {
    bar: 'Selection actions',
    barAnnounce: 'Selection actions, F6',
    highlightIn: (color: string, lastUsed: boolean) =>
      `Highlight ${color.toLowerCase()}${lastUsed ? ', last used (H or ⇧⌘H)' : ''}`,
    colorOption: (color: string, current: boolean) => `${color}${current ? ', current' : ''}`,
    note: 'Note',
    copy: 'Copy',
    search: 'Search',
    delete: 'Delete',
    copied: 'Copied',
    highlighted: (color: string) => `Highlighted ${color.toLowerCase()}`,
    deleted: 'Highlight deleted',
    noteDeleted: 'Note deleted',
    recolored: (color: string) => `Highlight changed to ${color.toLowerCase()}`,
    undo: 'Undo',
    restore: (quote: string) => `Restore highlight “${quote}”`,
    restoreNote: (quote: string) => `Restore note on “${quote}”`,
    restoreColor: (quote: string) => `Restore colour of “${quote}”`,
    noteTitle: (color: string) => `Note · ${color}`,
    noteLabel: 'Note on highlight',
    noteText: 'Note text',
    saving: 'Saving…',
    saved: 'Saved',
    notSaved: 'Not saved yet',
    noteHint: 'Saves as you type · Esc closes, focus returns to the text',
    copyNote: 'Copy quote and note',
    deleteNote: 'Delete highlight and note',
    done: 'Done',
    // Notes tab (A8; Screen 08)
    filter: 'Filter highlights and notes',
    all: 'All',
    only: (color: string) => `Only ${color.toLowerCase()}`,
    counts: (h: number, n: number) =>
      `${h} ${h === 1 ? 'highlight' : 'highlights'} · ${n} ${n === 1 ? 'note' : 'notes'}`,
    today: 'Today',
    yesterday: 'Yesterday',
    hasNote: 'Note',
    none: 'No highlights yet. Select text and choose a colour, or press H.',
    noMatches: 'No highlights match.',
    couldntPlace: 'Couldn’t place',
    changedReason: 'The book file changed after this was saved.',
    reattach: 'Re-attach',
    // G11 (PROVISIONAL): re-attaching by selecting the passage again
    reattachPrompt: (quote: string) => `Select the passage for “${quote}”`,
    attachHere: 'Attach here',
    cancel: 'Cancel',
    reattached: 'Highlight re-attached',
    unplacedAfterUpdate: (n: number) =>
      `${n} ${n === 1 ? 'highlight' : 'highlights'} couldn’t be placed in the updated book`,
    show: 'Show',
  },
  goto: {
    label: 'Go to location',
    percent: 'Percent',
    chapter: 'Chapter',
    page: 'Print page',
    percentLabel: 'Percent of book',
    chapterLabel: 'Chapter',
    pageLabel: 'Print page',
    go: 'Go',
    stays: 'Your current place stays in Back history (⌘[).',
    percentIn: (pct: number) => `${pct}% is in `,
    pageIn: (page: string) => `Page ${page} is in `,
    chapterAt: (pct: number) => ` starts at ${pct}%.`,
    noPage: (page: string) => `There is no page ${page} in this book.`,
    pageListOnly: 'Print page is available only when the book includes a page list.',
    open: 'Go to…',
    scrubber: 'Position in book',
  },
  peek: {
    label: (n: string) => `Note ${n}`,
    title: (n: string) => `Note ${n}`,
    hint: 'Esc closes · focus returns to the marker',
    openInPlace: 'Open note in place',
    copy: 'Copy',
    copied: 'Note copied',
    missing: 'This note couldn’t be found in the book.',
  },
  // C4 shortcut remapping (1.1, approved 2026-10-01)
  shortcuts: {
    intro:
      'Give any command a shortcut, including commands from extensions. Shortcuts need ⌘, ⌃ or ⌥ (function keys work alone); extensions can’t take Linen’s own.',
    none: 'None',
    change: 'Change',
    cancel: 'Cancel',
    remove: 'Remove',
    reset: 'Reset',
    resetAll: 'Reset All Shortcuts',
    typeNow: 'Type a shortcut…',
    changeFor: (title: string) => `Change the shortcut for ${title}`,
    removeFor: (title: string) => `Remove the shortcut for ${title}`,
    resetFor: (title: string) => `Reset the shortcut for ${title}`,
    needsModifier: 'A shortcut needs ⌘, ⌃ or ⌥ (function keys work alone).',
    reserved: (keys: string) => `${keys} belongs to macOS or Linen and can’t be changed.`,
    taken: (keys: string, title: string) =>
      `${keys} is Linen’s shortcut for ${title}; extensions can’t take it.`,
    moved: (keys: string, title: string) => `${keys} no longer runs ${title}.`,
  },
  // 1.1 dictionary peek (approved 2026-10-01)
  lookUp: {
    action: 'Look Up',
    label: (word: string) => `Definition of ${word}`,
    title: 'Dictionary',
    hint: 'Esc closes',
    looking: 'Looking up…',
    none: (word: string) => `No dictionary on this Mac has “${word}”.`,
    openDictionary: 'Open in Dictionary',
    searchBook: 'Search the book',
    contextMenu: (word: string) => `Look Up “${word.length > 24 ? word.slice(0, 23) + '…' : word}”`,
  },
  image: {
    label: 'Image',
    close: 'Close image',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit',
  },
  cheatSheet: {
    title: 'Keyboard shortcuts',
    close: 'Close',
    singleKeys:
      'Single-key shortcuts (such as [ and ]) work when the book text has focus and no screen reader is running.',
  },
  palette: {
    label: 'Command palette',
    placeholder: 'Type a command, chapter or setting',
    recentlyClosed: 'Recently closed',
    reading: 'Reading',
    chapters: 'Chapters',
    none: 'No matching commands',
    move: 'move',
    run: 'run',
    all: 'all shortcuts',
  },
  messages: {
    region: 'Message',
    dismiss: 'Dismiss',
    saveFailed: 'Couldn’t save notes to disk',
    retry: 'Retry',
    // N5, E5: wording PROVISIONAL (docs/pending-approvals.md).
    quitUnsaved: 'Some notes aren’t saved, so Linen stayed open',
    quitAnyway: 'Quit Anyway',
  },
  commands: {
    'chapter.next': 'Next chapter',
    'chapter.previous': 'Previous chapter',
    'search.open': 'Search in book',
    'search.next': 'Next result',
    'search.previous': 'Previous result',
    'navigator.contents': 'Go to chapter…',
    'goto.open': 'Go to location…',
    'navigator.notes': 'Highlights and notes',
    'selection.highlight': 'Highlight selection',
    'selection.note': 'Add note to selection',
    'selection.focusBar': 'Move to selection actions',
    'reader.caretBrowsing': 'Caret browsing',
    'text.larger': 'Larger text',
    'text.smaller': 'Smaller text',
    'text.reset': 'Default text size',
    'layout.pages': 'Pages Mode',
    'layout.scroll': 'Scroll Mode',
    'reader.settings': 'Reading settings…',
    'reader.simplifyStyles': 'Simplify Styles for This Book',
    'selection.lookUp': 'Look Up Selection',
    'app.settings': 'Settings…',
    'palette.open': 'Command palette',
    'shortcuts.show': 'Keyboard shortcuts',
    'history.back': 'Back',
    'library.show': 'Library',
    'book.open': 'Open…',
    'window.fullScreen': 'Full screen',
    'edit.undo': 'Undo',
    'layer.close': 'Close layer',
  },
} as const

export const t = en
