// The English message catalogue (B10): every UI string lives here, so the UI can
// be translated later. No translations or RTL UI mirroring in the MVP.

const fileName = (path: string) => path.split('/').pop() ?? path

export const en = {
  library: {
    emptyTitle: 'Your library is empty',
    emptyBody: 'Drop EPUB files here, or open one from your computer.',
    openBook: 'Open a book…',
    open: 'Open…',
    note: 'Books are copied into your library and stay on this device.',
    title: 'Library',
    count: (n: number) => `${n} ${n === 1 ? 'book' : 'books'}`,
    unknownAuthor: 'Unknown author',
    damaged: (n: number) => `${n} damaged`,
    new: 'New',
    finished: 'Finished',
    percent: (fraction: number) => `${Math.round(fraction * 100)}%`,
  },
  // Import outcomes: wording PROVISIONAL until the G4 designs exist.
  import: {
    addedDamaged: (title: string, n: number) =>
      `“${title}” was added · ${n} damaged ${n === 1 ? 'chapter' : 'chapters'}`,
    alreadyInLibrary: (path: string) => `“${fileName(path)}” is already in your library`,
    replaced: (title: string) => `“${title}” was updated from a newer file`,
    drm: (path: string) => `“${fileName(path)}” is protected by DRM and can’t be opened in Linen`,
    hostile: (path: string) => `“${fileName(path)}” couldn’t be opened safely and wasn’t added`,
    rejected: (path: string, reason: string) =>
      `“${fileName(path)}” couldn’t be opened · ${reason}`,
    fileFilter: 'EPUB',
  },
  reader: {
    library: 'Library',
    more: 'More',
    contents: 'Contents',
    previousPage: 'Previous page',
    nextPage: 'Next page',
    minutesLeft: (n: number) => `${n} min left in chapter`,
    resumedIn: (chapter: string) => `Resumed in ${chapter}`,
    resumed: 'Resumed where you left off',
    goToBeginning: 'Go to beginning',
    backToPage: (page: string) => `Back to page ${page}`,
    back: 'Back',
    pageAnnouncement: (page: number) => `Page ${page}`,
    pageAnnouncementApprox: (page: number) => `About page ${page}`,
    /** An estimated page number (L16), e.g. in “Back to page ≈312”. */
    approxPage: (page: number) => `≈${page}`,
    /** G8: fixed-layout books show their real pages, exactly. */
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `Pages ${pages[0]}–${pages[pages.length - 1]} of ${total}`
        : `Page ${pages[0]} of ${total}`,
    zoomLevel: (zoom: number) => `${Math.round(zoom * 100)}%`,
    zoomFit: 'Fit',
    /** G8: shown only when opening takes over 500 ms. */
    opening: (title: string) => `Opening “${title}”…`,
  },
  search: {
    label: 'Search in book',
    placeholder: 'Search in book',
    clear: 'Clear search',
    count: (n: number, chapters: number) =>
      `${n} ${n === 1 ? 'result' : 'results'} in ${chapters} ${chapters === 1 ? 'chapter' : 'chapters'}`,
    soFar: 'so far',
    searching: (n: number, of: number) => `Searching ${n} of ${of} chapters`,
    showAll: (n: number) => `Show all ${n}`,
    none: (q: string) => `No results for “${q}”`,
    next: 'next',
    previous: 'previous',
    back: 'back to your page',
    result: (i: number, n: number, chapter: string) =>
      [`Result ${i} of ${n}`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: 'Navigator',
    tabs: 'Navigator sections',
    search: 'Search',
    close: 'Close navigator',
    contents: 'Contents',
    loading: 'Reading the contents…',
    generated: 'Generated from headings',
    youAreHere: 'You are here',
    damaged: 'Damaged',
  },
  goto: {
    label: 'Go to location',
    percent: 'Percent',
    chapter: 'Chapter',
    page: 'Print page',
    percentLabel: 'Percent of book',
    chapterLabel: 'Chapter',
    pageLabel: 'Print page',
    go: 'Go',
    stays: 'Your current place stays in Back history (⌘[).',
    percentIn: (pct: number) => `${pct}% is in `,
    pageIn: (page: string) => `Page ${page} is in `,
    chapterAt: (pct: number) => ` starts at ${pct}%.`,
    noPage: (page: string) => `There is no page ${page} in this book.`,
    pageListOnly: 'Print page is available only when the book includes a page list.',
    open: 'Go to…',
    scrubber: 'Position in book',
  },
  peek: {
    label: (n: string) => `Note ${n}`,
    title: (n: string) => `Note ${n}`,
    hint: 'Esc closes · focus returns to the marker',
    openInPlace: 'Open note in place',
    copy: 'Copy',
    copied: 'Note copied',
    missing: 'This note couldn’t be found in the book.',
  },
  image: {
    label: 'Image',
    close: 'Close image',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    fit: 'Fit',
  },
  cheatSheet: {
    title: 'Keyboard shortcuts',
    close: 'Close',
    singleKeys:
      'Single-key shortcuts (such as [ and ]) work when the book text has focus and no screen reader is running.',
  },
  palette: {
    label: 'Command palette',
    placeholder: 'Type a command, chapter or setting',
    recentlyClosed: 'Recently closed',
    reading: 'Reading',
    chapters: 'Chapters',
    none: 'No matching commands',
    move: 'move',
    run: 'run',
    all: 'all shortcuts',
  },
  messages: {
    region: 'Message',
    dismiss: 'Dismiss',
    saveFailed: 'Couldn’t save notes to disk',
    retry: 'Retry',
  },
  commands: {
    'chapter.next': 'Next chapter',
    'chapter.previous': 'Previous chapter',
    'search.open': 'Search in book',
    'search.next': 'Next result',
    'search.previous': 'Previous result',
    'navigator.contents': 'Go to chapter…',
    'goto.open': 'Go to location…',
    'navigator.notes': 'Highlights and notes',
    'selection.highlight': 'Highlight selection',
    'selection.note': 'Add note to selection',
    'selection.focusBar': 'Move to selection actions',
    'reader.caretBrowsing': 'Caret browsing',
    'text.larger': 'Larger text',
    'text.smaller': 'Smaller text',
    'text.reset': 'Default text size',
    'layout.pages': 'Pages Mode',
    'layout.scroll': 'Scroll Mode',
    'palette.open': 'Command palette',
    'shortcuts.show': 'Keyboard shortcuts',
    'history.back': 'Back',
    'library.show': 'Library',
    'book.open': 'Open…',
    'window.fullScreen': 'Full screen',
    'edit.undo': 'Undo',
    'layer.close': 'Close layer',
  },
} as const

export const t = en
