// The Spanish catalogue: one neutral Spanish, addressing the reader as tú (L-1,
// L-3). A machine draft (2026-10-07, L-6): it follows docs/i18n/style.md and
// docs/i18n/glossary.md and waits for a native speaker's review in context
// before it ships. Keys, values and context: en.ts.

import { formatPercent, plural } from './format'
import type { Messages } from './types'

const fileName = (path: string) => path.split('/').pop() ?? path

export const es: Messages = {
  library: {
    emptyTitle: 'Tu biblioteca está vacía',
    emptyBody: 'Arrastra archivos EPUB aquí o abre uno desde tu Mac.',
    openBook: 'Abrir un libro…',
    open: 'Abrir…',
    note: 'Los libros se copian en tu biblioteca y se quedan en este dispositivo.',
    title: 'Biblioteca',
    count: (n: number) => plural(n, { one: `${n} libro`, other: `${n} libros` }),
    unknownAuthor: 'Autor desconocido',
    damaged: (n: number) => plural(n, { one: `${n} dañado`, other: `${n} dañados` }),
    new: 'Nuevo',
    finished: 'Terminado',
    percent: (fraction: number) => formatPercent(fraction),
    search: 'Buscar en la biblioteca',
    searchPlaceholder: 'Buscar por título o autor',
    sortBy: (label: string) => `Ordenar por: ${label}`,
    sorts: { recent: 'Recientes', title: 'Título', author: 'Autor' },
    view: 'Visualización',
    viewGrid: 'Portadas',
    viewList: 'Lista',
    neverOpened: '—',
    continueReading: 'Seguir leyendo',
    openedAt: (day: string, time: string) => `Abierto ${day} a las ${time}`,
    openedAgo: (ago: string) => `Abierto ${ago}`,
    allBooks: 'Todos los libros',
    resume: 'Seguir leyendo',
    itemMenu: (title: string) => `Más opciones para “${title}”`,
    info: 'Información del libro',
    showFile: 'Mostrar en el Finder',
    remove: 'Eliminar',
    removed: (title: string) => `Se eliminó “${title}”`,
    restore: (title: string) => `Restaurar “${title}”`,
    noMatches: (q: string) => `Ningún libro coincide con “${q}”`,
    damagedTitle: 'No se pudo abrir una parte de este libro',
    damagedBody: (n: number, total: number) =>
      `${total ? `${n} de ${total}` : n} ${plural(total || n, { one: 'capítulo está dañado', other: 'capítulos están dañados' })}. Puedes leer el resto; los capítulos dañados aparecen marcados en el índice para que no falte nada sin que lo sepas.`,
    damagedFile: (title: string, size: string) => `${title} · ${size}`,
    readAnyway: 'Leer de todos modos',
    showFileShort: 'Mostrar archivo',
    clear: 'Borrar',
    webkitTitle: 'Los libros necesitan un Safari más reciente',
    webkitBody:
      'Linen muestra los libros con el motor web de la propia Mac, que viene con Safari. Esta Mac tiene una versión más antigua de la que Linen necesita: Safari 16.4 o posterior. Actualízalo en Actualización de software y vuelve a abrir el libro. Tu biblioteca y tus notas están a salvo.',
    webkitUpdate: 'Abrir Actualización de software',
    webkitClose: 'Ahora no',
  },
  prefs: {
    title: 'Ajustes',
    sections: {
      general: 'General',
      reading: 'Lectura',
      library: 'Biblioteca',
      extensions: 'Extensiones',
      shortcuts: 'Funciones rápidas',
      about: 'Acerca de',
    },
    theme: 'Tema',
    atLaunch: 'Al abrir Linen',
    atLaunchLibrary: 'Mostrar la biblioteca',
    atLaunchBook: 'Volver a abrir el último libro',
    language: 'Idioma',
    languageSystem: (name: string) => `Sistema (${name})`,
    languageRestart: 'Linen usará el nuevo idioma después de reiniciarse.',
    restartNow: 'Reiniciar ahora',
    textSize: 'Tamaño del texto',
    lineSpacing: 'Interlineado',
    font: 'Tipo de letra',
    pageWidth: 'Ancho de página',
    publisherStyles: 'Estilos de la editorial',
    publisherFull: 'Completos',
    publisherBalanced: 'Equilibrados',
    publisherOff: 'Desactivados',
    publisherHelp:
      '“Equilibrados” conserva el diseño del libro, pero usa tu interlineado y tu alineación. “Completos” lo conserva todo; “Desactivados” muestra texto simple. Puedes simplificar un libro desde su menú ⋯.',
    crossfade: 'Fundido al pasar página',
    crossfadeHelp: 'Las páginas se funden entre sí durante 120 ms en lugar de cambiar de golpe.',
    announcements: 'Anunciar los cambios de página',
    announcementsHelp: 'Los lectores de pantalla dicen “Página N” después de cada cambio.',
    folder: 'Carpeta de la biblioteca',
    folderHelp:
      'Tus libros, portadas, resaltados y notas están en esta carpeta. Haz una copia de seguridad para conservarlos; Time Machine la hace.',
    showFolder: 'Mostrar en el Finder',
    exportAll: 'Exportar todos los resaltados y notas…',
    exportHelp: 'Un archivo W3C Web Annotation por libro, que otras apps pueden leer.',
    exported: (n: number) =>
      plural(n, { one: `Se exportó ${n} libro`, other: `Se exportaron ${n} libros` }),
    nothingToExport: 'No hay resaltados para exportar.',
    uninstall:
      'Si eliminas Linen de Aplicaciones, esta carpeta se queda donde está. Elimínala también para borrar tu biblioteca.',
    extensionsIntro:
      'Las extensiones añaden acciones, paneles, temas y exportadores en lugares fijos. No pueden cambiar el aspecto de las páginas ni leer tus libros o notas sin tu permiso.',
    extensionsNone: 'Las extensiones llegarán en una versión futura.',
    singleKeys: 'Funciones rápidas de una tecla',
    singleKeysHelp:
      'Teclas como [ ] H y N funcionan mientras el texto tiene el foco. Se desactivan solas mientras se usa un lector de pantalla.',
    showShortcuts: 'Mostrar todas las funciones rápidas',
    version: (v: string) => `Versión ${v}`,
    aboutLine: 'Un lector de EPUB tranquilo. Tus libros se quedan en este dispositivo.',
    fonts: 'Literata y OpenDyslexic se distribuyen con la licencia SIL Open Font License.',
    privacy:
      'Linen no envía nada a ningún sitio. Si algo sale mal, los detalles se escriben en un registro de fallos en esta Mac, que puedes adjuntar a un correo si quieres.',
    showCrashLog: 'Mostrar el registro de fallos',
  },
  extensions: {
    stopped: (name: string) => `${name} dejó de responder`,
    restart: 'Reiniciar',
    notResponding: 'No responde',
    restartNamed: (name: string) => `Reiniciar ${name}`,
    manage: 'Gestionar extensiones…',
    more: 'Más acciones de extensiones',
    via: (name: string) => `con la extensión ${name}`,
    exported: 'Exportado',
    exportFailed: (name: string) => `${name} no pudo exportar`,
  },
  extSettings: {
    install: 'Instalar desde un archivo…',
    builtin: 'Integrada',
    themePack: 'Paquete de temas',
    off: 'Desactivada',
    canAccess: 'Puede acceder a',
    adds: 'Añade',
    can: 'Puede',
    nothing: 'Nada: los temas no contienen código',
    noAccess: 'Nada más allá de su propio almacenamiento',
    enabled: (name: string) => `${name} activada`,
    failures: (n: number) =>
      plural(n, {
        one: `Dejó de responder ${n} vez hace poco y se reinició. La lectura no se vio afectada.`,
        other: `Dejó de responder ${n} veces hace poco y se reinició. La lectura no se vio afectada.`,
      }),
    suspended:
      'Dejó de responder tres veces en diez minutos y se pausó. La lectura no se vio afectada.',
    restart: 'Reiniciar',
    disable: 'Desactivar',
    incompatible: (why: string) => `Desactivada: ${why}.`,
    remove: 'Eliminar…',
    pin: 'Mostrar sus comandos en el menú ⋯',
    restartWithout: 'Reiniciar sin extensiones',
    shiftHint: 'También puedes mantener pulsada ⇧ mientras se abre Linen.',
    safeMode: 'Linen se abrió sin extensiones. Volverán la próxima vez que se abra.',
    installTitle: (name: string) => `¿Instalar “${name}”?`,
    updateTitle: (name: string, version: string) => `“${name}” ${version} pide más acceso`,
    notVerified:
      'Linen no la ha verificado. Instala extensiones solo de personas en las que confíes.',
    newAccess: 'Acceso nuevo',
    cancel: 'Cancelar',
    installButton: 'Instalar',
    update: 'Actualizar',
    keepCurrent: 'Conservar la versión actual',
    cantInstall: (name: string) => `No se puede instalar “${name}”`,
    close: 'Cerrar',
    installed: (name: string) => `Se instaló “${name}”`,
    removeTitle: (name: string) => `¿Eliminar “${name}”?`,
    removeBody:
      '¿Eliminar también lo que guardó? Si lo conservas, volverá si instalas la extensión de nuevo.',
    keepData: 'Conservar sus datos',
    deleteData: 'Eliminar sus datos',
    fileFilter: 'Extensión de Linen',
    permissions: {
      'book.metadata': 'Ver el título y el autor del libro',
      'book.selection': 'Leer el texto que selecciones',
      'book.text': 'Leer el libro completo',
      'annotations.read': 'Leer resaltados y notas',
      'annotations.write': 'Cambiar resaltados y notas',
      'library.read': 'Ver todos los libros de tu biblioteca',
      'reading.sessions': 'Saber cuándo y cuánto tiempo lees',
      'files.import': 'Abrir los archivos que elijas',
      'files.export': 'Guardar en los archivos que elijas',
      background: 'Ejecutarse en segundo plano',
    },
    connect: (host: string) => `Conectarse a ${host}`,
    connectAny: (suffix: string) => `Conectarse a cualquier dirección que termine en ${suffix}`,
    commandsAdded: (n: number) => plural(n, { one: 'Comando', other: `${n} comandos` }),
    inSelectionMenu: (title: string) => `“${title}” en el menú de selección`,
    inLookupMenu: (title: string) => `“${title}” en la ventana de consulta`,
    navigatorTab: 'Pestaña del navegador',
    themesAdded: (n: number) => plural(n, { one: 'Tema', other: `${n} temas` }),
    exportInNotes: 'Exportar en Notas',
  },
  info: {
    label: 'Información del libro',
    done: 'OK',
    by: 'Autor',
    publisher: 'Editorial',
    published: 'Publicado',
    language: 'Idioma',
    identifier: 'Identificador',
    added: 'Añadido',
    fileSize: 'Tamaño del archivo',
    layout: 'Diseño',
    fixed: 'Páginas fijas',
    reflowable: 'Adaptable',
    accessibility: 'Accesibilidad',
    noAccessibility: 'El libro no incluye información de accesibilidad.',
    description: 'Descripción',
    sizeMB: (n: string) => `${n} MB`,
    sizeKB: (n: string) => `${n} KB`,
    a11y: {
      accessMode: {
        textual: 'Se puede leer como texto',
        visual: 'Tiene contenido visual',
        auditory: 'Tiene contenido de audio',
      },
      accessModeSufficient: {
        textual: 'Se puede leer completo como texto',
        visual: 'Parte del contenido requiere la vista',
      },
      accessibilityFeature: {
        alternativeText: 'Tiene texto alternativo para las imágenes',
        longDescription: 'Tiene descripciones largas para imágenes complejas',
        tableOfContents: 'Tiene índice',
        readingOrder: 'Tiene un orden de lectura lógico',
        structuralNavigation: 'Tiene encabezados para navegar',
        pageBreakMarkers: 'Marca las páginas impresas',
        printPageNumbers: 'Marca las páginas impresas',
        MathML: 'Tiene matemáticas en MathML',
        displayTransformability: 'El texto se puede cambiar de estilo',
        synchronizedAudioText: 'Tiene audio de lectura en voz alta',
        ARIA: 'Usa roles ARIA',
        index: 'Tiene índice alfabético',
        captions: 'Tiene subtítulos',
      },
      accessibilityHazard: {
        none: 'Sin riesgos conocidos',
        noFlashingHazard: 'Sin riesgo de destellos',
        noMotionSimulationHazard: 'Sin riesgo de movimiento',
        noSoundHazard: 'Sin riesgo sonoro',
        flashing: 'Advertencia: contenido con destellos',
        motionSimulation: 'Advertencia: simulación de movimiento',
        sound: 'Advertencia: sonido',
        unknown: 'Riesgos desconocidos',
      },
    },
  },
  update: {
    ready: (version: string) => `Actualización lista · Linen ${version}`,
    restart: 'Reiniciar',
    available: (version: string) => `Linen ${version} está disponible`,
    download: 'Descargar',
  },
  import: {
    addedDamaged: (title: string, n: number) =>
      `Se añadió “${title}” · ${plural(n, { one: `${n} capítulo dañado`, other: `${n} capítulos dañados` })}`,
    alreadyInLibrary: (path: string) => `“${fileName(path)}” ya está en tu biblioteca`,
    replaced: (title: string) => `Se actualizó “${title}” con un archivo más reciente`,
    drm: (path: string) =>
      `“${fileName(path)}” está protegido con DRM y no se puede abrir en Linen`,
    hostile: (path: string) =>
      `“${fileName(path)}” no se pudo abrir de forma segura y no se añadió`,
    rejected: (path: string, reason: string) => `No se pudo abrir “${fileName(path)}” · ${reason}`,
    fileFilter: 'EPUB',
    reasons: {
      not_zip: 'no es un archivo zip o el archivo está incompleto',
      too_many_entries: (max: string) => `más de ${max} elementos`,
      too_large: 'el tamaño sin comprimir supera 1 GB',
      compression_ratio: (entry: string, ratio: string) =>
        `el elemento ${entry} se comprime más de ${ratio}:1`,
      unsafe_path: (entry: string) => `ruta de elemento no segura ${entry}`,
      symlink: (entry: string) => `elemento que es un enlace simbólico ${entry}`,
      no_package: 'no hay container.xml ni documento de paquete',
      bad_package: 'el documento de paquete no es XML bien formado',
      xml_entities: (entry: string) => `${entry} declara entidades XML`,
      drm: (entry: string) => `contenido cifrado (DRM) en ${entry}`,
      no_chapters: 'no se pudo abrir ningún capítulo del libro',
    },
  },
  reader: {
    simplified: 'Los estilos de este libro están simplificados',
    unsimplified: 'Este libro vuelve a tener sus propios estilos',
    undo: 'Deshacer',
    library: 'Biblioteca',
    more: 'Más',
    caretOn:
      'Navegación con cursor activada. Las flechas mueven el cursor; Mayúsculas y las flechas seleccionan.',
    caretOff: 'Navegación con cursor desactivada',
    contents: 'Índice',
    previousPage: 'Página anterior',
    nextPage: 'Página siguiente',
    minutesLeft: (n: number) => `Quedan ${n} min en el capítulo`,
    resumedIn: (chapter: string) => `Se reanudó en ${chapter}`,
    resumed: 'Se reanudó donde lo dejaste',
    goToBeginning: 'Ir al principio',
    backToPage: (page: string) => `Volver a la página ${page}`,
    back: 'Atrás',
    pageAnnouncement: (page: number) => `Página ${page}`,
    pageAnnouncementApprox: (page: number) => `Página ${page} aproximadamente`,
    approxPage: (page: number) => `≈${page}`,
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `Páginas ${pages[0]}–${pages[pages.length - 1]} de ${total}`
        : `Página ${pages[0]} de ${total}`,
    zoomLevel: (zoom: number) => formatPercent(zoom),
    zoomFit: 'Ajustar',
    opening: (title: string) => `Abriendo “${title}”…`,
  },
  search: {
    label: 'Buscar en el libro',
    placeholder: 'Buscar en el libro',
    clear: 'Borrar la búsqueda',
    count: (n: number, chapters: number) =>
      `${plural(n, { one: `${n} resultado`, other: `${n} resultados` })} en ${plural(chapters, { one: `${chapters} capítulo`, other: `${chapters} capítulos` })}`,
    soFar: 'por ahora',
    searching: (n: number, of: number) => `Buscando en el capítulo ${n} de ${of}`,
    showAll: (n: number) => `Mostrar los ${n}`,
    none: (q: string) => `No hay resultados para “${q}”`,
    options: 'Opciones de búsqueda',
    wholeWords: 'Palabras completas',
    regex: 'Expresión regular',
    invalid: 'Esta expresión regular no es válida.',
    next: 'siguiente',
    previous: 'anterior',
    back: 'volver a tu página',
    result: (i: number, n: number, chapter: string) =>
      [`Resultado ${i} de ${n}`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: 'Navegador',
    tabs: 'Secciones del navegador',
    search: 'Buscar',
    notes: 'Notas',
    more: 'Más',
    close: 'Cerrar el navegador',
    contents: 'Índice',
    loading: 'Leyendo el índice…',
    generated: 'Generado a partir de los encabezados',
    youAreHere: 'Estás aquí',
    damaged: 'Dañado',
  },
  aa: {
    label: 'Ajustes de lectura',
    button: 'Ajustes de lectura',
    textSize: 'Tamaño del texto',
    sizeScope: (px: number) => `${px} px · Todos los libros`,
    px: (px: number) => `${px} píxeles`,
    theme: 'Tema',
    paper: 'Papel',
    sepia: 'Sepia',
    night: 'Noche',
    auto: 'Auto',
    lineSpacing: 'Interlineado',
    compact: 'Compacto',
    normal: 'Normal',
    loose: 'Amplio',
    layout: 'Diseño',
    pages: 'Páginas',
    scroll: 'Desplazar',
    allBooks: 'Todos los libros',
    thisBook: 'Este libro',
    moreSettings: 'Más en Ajustes…',
    anywhere: '⌘+ ⌘− siempre funcionan',
    codeHint: 'Gran parte de este libro es código o tablas. Puede leerse mejor desplazándote.',
    fixedLayout:
      'Este libro tiene páginas fijas, así que el tamaño del texto y el espaciado no pueden cambiar. ⌘+ y ⌘− amplían la página.',
    font: 'Tipo de letra',
    fontBook: 'Libro',
    fontLiterata: 'Literata',
    fontSans: 'Sans',
    fontDyslexic: 'Dislexia',
    fontDyslexicLong: 'OpenDyslexic',
    width: 'Ancho de página',
    narrow: 'Estrecho',
    wide: 'Ancho',
  },
  annotations: {
    bar: 'Acciones de la selección',
    barAnnounce: 'Acciones de la selección, F6',
    highlightIn: (color: string, lastUsed: boolean) =>
      `Resaltar en ${color}${lastUsed ? ', el último usado (H o ⇧⌘H)' : ''}`,
    colorOption: (color: string, current: boolean) => `${color}${current ? ', actual' : ''}`,
    note: 'Nota',
    copy: 'Copiar',
    search: 'Buscar',
    delete: 'Eliminar',
    copied: 'Copiado',
    highlighted: (color: string) => `Resaltado en ${color}`,
    deleted: 'Se eliminó el resaltado',
    noteDeleted: 'Se eliminó la nota',
    recolored: (color: string) => `El resaltado cambió a ${color}`,
    highlightCommand: (color: string) => `Resaltar en ${color}`,
    undo: 'Deshacer',
    restore: (quote: string) => `Restaurar el resaltado “${quote}”`,
    restoreNote: (quote: string) => `Restaurar la nota de “${quote}”`,
    restoreColor: (quote: string) => `Restaurar el color de “${quote}”`,
    noteTitle: (color: string) => `Nota · ${color}`,
    noteLabel: 'Nota del resaltado',
    noteText: 'Texto de la nota',
    saving: 'Guardando…',
    saved: 'Guardada',
    notSaved: 'Aún no se ha guardado',
    noteHint: 'Se guarda mientras escribes · Esc cierra y el foco vuelve al texto',
    copyNote: 'Copiar la cita y la nota',
    deleteNote: 'Eliminar el resaltado y la nota',
    done: 'OK',
    filter: 'Filtrar resaltados y notas',
    all: 'Todos',
    only: (color: string) => `Solo ${color}`,
    counts: (h: number, n: number) =>
      `${plural(h, { one: `${h} resaltado`, other: `${h} resaltados` })} · ${plural(n, { one: `${n} nota`, other: `${n} notas` })}`,
    today: 'Hoy',
    yesterday: 'Ayer',
    hasNote: 'Nota',
    none: 'Aún no hay resaltados. Selecciona texto y elige un color, o pulsa H.',
    noMatches: 'Ningún resaltado coincide.',
    couldntPlace: 'No se pudo ubicar',
    changedReason: 'El archivo del libro cambió después de guardarse esto.',
    reattach: 'Volver a ubicar',
    reattachPrompt: (quote: string) => `Selecciona el pasaje de “${quote}”`,
    attachHere: 'Ubicar aquí',
    cancel: 'Cancelar',
    reattached: 'Se volvió a ubicar el resaltado',
    unplacedAfterUpdate: (n: number) =>
      plural(n, {
        one: `${n} resaltado no se pudo ubicar en el libro actualizado`,
        other: `${n} resaltados no se pudieron ubicar en el libro actualizado`,
      }),
    show: 'Mostrar',
  },
  colors: { yellow: 'Amarillo', green: 'Verde', blue: 'Azul', rose: 'Rosa' },
  colorsInText: { yellow: 'amarillo', green: 'verde', blue: 'azul', rose: 'rosa' },
  goto: {
    label: 'Ir a una ubicación',
    percent: 'Porcentaje',
    chapter: 'Capítulo',
    page: 'Página impresa',
    percentLabel: 'Porcentaje del libro',
    chapterLabel: 'Capítulo',
    pageLabel: 'Página impresa',
    go: 'Ir',
    stays: 'Tu posición actual se queda en el historial de Atrás (⌘[).',
    percentIn: (pct: number) => `El ${formatPercent(pct / 100)} está en `,
    pageIn: (page: string) => `La página ${page} está en `,
    chapterAt: (pct: number) => ` empieza en el ${formatPercent(pct / 100)}.`,
    sentenceEnd: '. ',
    noPage: (page: string) => `Este libro no tiene página ${page}.`,
    pageListOnly:
      'La página impresa solo está disponible si el libro incluye una lista de páginas.',
    open: 'Ir a…',
    scrubber: 'Posición en el libro',
  },
  peek: {
    label: (n: string) => `Nota ${n}`,
    title: (n: string) => `Nota ${n}`,
    hint: 'Esc cierra · el foco vuelve a la marca',
    openInPlace: 'Abrir la nota en su lugar',
    copy: 'Copiar',
    copied: 'Nota copiada',
    missing: 'No se encontró esta nota en el libro.',
  },
  shortcuts: {
    intro:
      'Asigna una función rápida a cualquier comando, incluidos los de las extensiones. Las funciones rápidas necesitan ⌘, ⌃ o ⌥ (las teclas de función sirven solas); las extensiones no pueden usar las de Linen.',
    none: 'Ninguna',
    change: 'Cambiar',
    cancel: 'Cancelar',
    remove: 'Eliminar',
    reset: 'Restablecer',
    resetAll: 'Restablecer todas las funciones rápidas',
    typeNow: 'Escribe una función rápida…',
    changeFor: (title: string) => `Cambiar la función rápida de ${title}`,
    removeFor: (title: string) => `Eliminar la función rápida de ${title}`,
    resetFor: (title: string) => `Restablecer la función rápida de ${title}`,
    needsModifier: 'Una función rápida necesita ⌘, ⌃ o ⌥ (las teclas de función sirven solas).',
    reserved: (keys: string) => `${keys} pertenece a macOS o a Linen y no se puede cambiar.`,
    taken: (keys: string, title: string) =>
      `${keys} es la función rápida de Linen para ${title}; las extensiones no pueden usarla.`,
    moved: (keys: string, title: string) => `${keys} ya no ejecuta ${title}.`,
  },
  lookUp: {
    action: 'Consultar',
    label: (word: string) => `Definición de ${word}`,
    title: 'Diccionario',
    hint: 'Esc cierra',
    looking: 'Consultando…',
    none: (word: string) => `Ningún diccionario de esta Mac tiene “${word}”.`,
    openDictionary: 'Abrir en Diccionario',
    searchBook: 'Buscar en el libro',
    contextMenu: (word: string) =>
      `Consultar “${word.length > 24 ? word.slice(0, 23) + '…' : word}”`,
  },
  // Reading Lens (PROVISIONAL; borrador automático, pendiente de revisión)
  lens: {
    macDictionaries: 'Diccionarios de esta Mac',
    labelMacDictionary: 'Diccionario · en esta Mac',
    labelAi: (model: string) => `Explicación con IA · ${model}`,
    labelDictionary: (name: string) => `Diccionario · ${name}`,
    explanationOf: (word: string) => `Explicación de “${word}”`,
    lookUpWord: (word: string) => `Consultar “${word}”`,
    lookUpWith: 'Consultar con',
    lookUpWithCommand: (title: string) => `Consultar con ${title}`,
    asking: (name: string) => `Preguntando a ${name}…`,
    copyExplanation: 'Copiar la explicación',
    copied: 'Explicación copiada',
    more: 'Más',
    less: 'Menos',
    whatWasSent: 'Qué se envió',
    sentBy: (name: string) => `Enviado por ${name}`,
    back: 'Atrás',
    searchInBook: 'Buscar en el libro',
    offline: 'No tienes conexión.',
    offlineDetail: (name: string) => `${name} necesita una conexión.`,
    timeout: (name: string) => `${name} no respondió en 10 segundos.`,
    unauthorized: (name: string) => `${name} no aceptó la clave.`,
    unauthorizedDetail: 'Puede haber caducado o haberse revocado.',
    rateLimited: (name: string) => `${name} está limitando las solicitudes.`,
    rateLimitedDetail: 'Vuelve a intentarlo en un minuto.',
    unavailable: (name: string) => `${name} no está disponible ahora.`,
    badAnswer: (name: string) => `${name} envió una respuesta que Linen no puede mostrar.`,
    stopped: (name: string) => `${name} dejó de responder.`,
    stoppedDetail: 'La lectura no se vio afectada.',
    continue: 'Continuar',
    notNow: 'Ahora no',
    tryAgain: 'Reintentar',
    restart: (name: string) => `Reiniciar ${name}`,
  },
  image: {
    label: 'Imagen',
    close: 'Cerrar la imagen',
    zoomIn: 'Ampliar',
    zoomOut: 'Reducir',
    fit: 'Ajustar',
  },
  cheatSheet: {
    title: 'Funciones rápidas de teclado',
    close: 'Cerrar',
    singleKeys:
      'Las funciones rápidas de una tecla (como [ y ]) funcionan cuando el texto del libro tiene el foco y no se está usando un lector de pantalla.',
    pages: 'Páginas',
    sections: {
      navigation: 'Navegación',
      reading: 'Lectura',
      search: 'Búsqueda',
      annotation: 'Resaltados y notas',
      view: 'Visualización',
      app: 'App',
      extension: 'Extensiones',
    },
    nextPage: 'Página siguiente',
    previousPage: 'Página anterior',
    scrollScreen: 'Desplazar una pantalla (modo Desplazamiento)',
    scrollLines: 'Desplazar por líneas (modo Desplazamiento)',
  },
  keys: { esc: 'Esc', space: 'Espacio', pageUp: 'RePág', pageDown: 'AvPág' },
  menus: {
    file: 'Archivo',
    edit: 'Edición',
    view: 'Visualización',
    go: 'Ir',
    window: 'Ventana',
    about: (app: string) => `Acerca de ${app}`,
    services: 'Servicios',
    hide: (app: string) => `Ocultar ${app}`,
    hideOthers: 'Ocultar otros',
    showAll: 'Mostrar todo',
    quit: (app: string) => `Salir de ${app}`,
    cut: 'Cortar',
    copy: 'Copiar',
    paste: 'Pegar',
    selectAll: 'Seleccionar todo',
    minimize: 'Minimizar',
  },
  palette: {
    label: 'Paleta de comandos',
    placeholder: 'Escribe un comando, un capítulo o un ajuste',
    recentlyClosed: 'Cerrado recientemente',
    reading: 'Lectura',
    chapters: 'Capítulos',
    none: 'Ningún comando coincide',
    move: 'mover',
    run: 'ejecutar',
    all: 'todas las funciones rápidas',
  },
  messages: {
    region: 'Mensaje',
    dismiss: 'Descartar',
    saveFailed: 'No se pudieron guardar las notas en el disco',
    retry: 'Reintentar',
    quitUnsaved: 'Algunas notas no están guardadas, así que Linen siguió abierto',
    quitAnyway: 'Salir de todos modos',
  },
  commands: {
    'chapter.next': 'Capítulo siguiente',
    'chapter.previous': 'Capítulo anterior',
    'search.open': 'Buscar en el libro',
    'search.next': 'Resultado siguiente',
    'search.previous': 'Resultado anterior',
    'navigator.contents': 'Ir a un capítulo…',
    'goto.open': 'Ir a una ubicación…',
    'navigator.notes': 'Resaltados y notas',
    'selection.highlight': 'Resaltar la selección',
    'selection.note': 'Añadir una nota a la selección',
    'selection.focusBar': 'Ir a las acciones de la selección',
    'reader.caretBrowsing': 'Navegación con cursor',
    'text.larger': 'Texto más grande',
    'text.smaller': 'Texto más pequeño',
    'text.reset': 'Tamaño de texto predeterminado',
    'layout.pages': 'Modo Páginas',
    'layout.scroll': 'Modo Desplazamiento',
    'reader.settings': 'Ajustes de lectura…',
    'reader.simplifyStyles': 'Simplificar estilos de este libro',
    'selection.lookUp': 'Consultar la selección',
    'app.settings': 'Ajustes…',
    'palette.open': 'Paleta de comandos',
    'shortcuts.show': 'Funciones rápidas de teclado',
    'history.back': 'Atrás',
    'library.show': 'Biblioteca',
    'book.open': 'Abrir…',
    'window.fullScreen': 'Pantalla completa',
    'edit.undo': 'Deshacer',
    'layer.close': 'Cerrar la capa',
  },
}
