// The Japanese catalogue (L-1). A machine draft (2026-10-07, L-6): it follows
// docs/i18n/style.md and docs/i18n/glossary.md and waits for a native speaker's
// review in context before it ships. Keys, values and context: en.ts.

import { formatPercent } from './format'
import type { Messages } from './types'

const fileName = (path: string) => path.split('/').pop() ?? path

export const ja: Messages = {
  library: {
    emptyTitle: 'ライブラリは空です',
    emptyBody: 'EPUB ファイルをここにドロップするか、コンピュータから開いてください。',
    openBook: 'ブックを開く…',
    open: '開く…',
    note: 'ブックはライブラリにコピーされ、このデバイスに保存されます。',
    title: 'ライブラリ',
    count: (n: number) => `${n}冊`,
    unknownAuthor: '著者不明',
    damaged: (n: number) => `${n}件が破損`,
    new: '新着',
    finished: '読了',
    percent: (fraction: number) => formatPercent(fraction),
    search: 'ライブラリを検索',
    searchPlaceholder: 'タイトルまたは著者を検索',
    sortBy: (label: string) => `並べ替え：${label}`,
    sorts: { recent: '最近', title: 'タイトル', author: '著者' },
    view: '表示',
    viewGrid: 'カバー',
    viewList: 'リスト',
    neverOpened: '—',
    continueReading: '続きを読む',
    openedAt: (day: string, time: string) => `${day}の${time}に開きました`,
    openedAgo: (ago: string) => `${ago}に開きました`,
    allBooks: 'すべてのブック',
    resume: '続きから読む',
    itemMenu: (title: string) => `「${title}」のその他の操作`,
    info: 'ブック情報',
    showFile: 'Finder に表示',
    remove: '削除',
    removed: (title: string) => `「${title}」を削除しました`,
    restore: (title: string) => `「${title}」を元に戻す`,
    noMatches: (q: string) => `「${q}」に一致するブックはありません`,
    damagedTitle: 'このブックの一部を開けませんでした',
    damagedBody: (n: number, total: number) =>
      `${total ? `${total}章中${n}章` : `${n}章`}が破損しています。残りは読むことができます。破損した章は目次に示されるので、何かが知らないうちに欠けることはありません。`,
    damagedFile: (title: string, size: string) => `${title} · ${size}`,
    readAnyway: 'このまま読む',
    showFileShort: 'ファイルを表示',
    clear: '消去',
    webkitTitle: 'ブックを読むには新しい Safari が必要です',
    webkitBody:
      'Linen は Safari に付属する Mac 自身の Web エンジンでブックを表示します。この Mac のバージョンは Linen に必要なもの（Safari 16.4 以降）より古いため、ソフトウェアアップデートでアップデートしてから、もう一度ブックを開いてください。ライブラリとメモは安全です。',
    webkitUpdate: 'ソフトウェアアップデートを開く',
    webkitClose: '後で',
  },
  prefs: {
    title: '設定',
    sections: {
      general: '一般',
      reading: '読書',
      library: 'ライブラリ',
      extensions: '機能拡張',
      shortcuts: 'ショートカット',
      about: '情報',
    },
    theme: 'テーマ',
    atLaunch: 'Linen を開いたとき',
    atLaunchLibrary: 'ライブラリを表示',
    atLaunchBook: '最後のブックを再び開く',
    language: '言語',
    languageSystem: (name: string) => `システム（${name}）`,
    languageRestart: '新しい言語は Linen の再起動後に使われます。',
    restartNow: '今すぐ再起動',
    textSize: '文字サイズ',
    lineSpacing: '行間',
    font: 'フォント',
    pageWidth: 'ページの幅',
    publisherStyles: '出版社のスタイル',
    publisherFull: 'すべて',
    publisherBalanced: 'バランス',
    publisherOff: 'オフ',
    publisherHelp:
      '「バランス」はブックのデザインを保ちつつ、行間と行揃えをあなたの設定にします。「すべて」はすべてを保ち、「オフ」はプレーンテキストで表示します。ブックごとに ⋯ メニューからスタイルを簡素化することもできます。',
    crossfade: 'ページめくりのクロスフェード',
    crossfadeHelp: 'ページは瞬時に切り替わる代わりに、120ミリ秒かけて重なりながら切り替わります。',
    announcements: 'ページめくりを読み上げる',
    announcementsHelp: 'めくるたびにスクリーンリーダーが「N ページ」と読み上げます。',
    folder: 'ライブラリフォルダ',
    folderHelp:
      'ブック、カバー、ハイライト、メモはすべてこのフォルダにあります。保管するにはバックアップしてください。Time Machine でもバックアップされます。',
    showFolder: 'Finder に表示',
    exportAll: 'すべてのハイライトとメモを書き出す…',
    exportHelp: 'ブックごとに1つの W3C Web Annotation ファイル。ほかのアプリでも読めます。',
    exported: (n: number) => `${n}冊のブックを書き出しました`,
    nothingToExport: '書き出すハイライトがありません。',
    uninstall:
      'アプリケーションフォルダから Linen を削除しても、このフォルダは残ります。ライブラリも削除するには、このフォルダも削除してください。',
    extensionsIntro:
      '機能拡張は、決められた場所にアクション、パネル、テーマ、書き出し機能を追加します。ページの見た目を変えることはできず、許可しない限りブックやメモを読むこともできません。',
    extensionsNone: '機能拡張は今後のバージョンで利用できるようになります。',
    singleKeys: '単一キーのショートカット',
    singleKeysHelp:
      '[ ] H N などのキーは、テキストにフォーカスがあるときに使えます。スクリーンリーダーの実行中は自動的にオフになります。',
    showShortcuts: 'すべてのショートカットを表示',
    version: (v: string) => `バージョン ${v}`,
    aboutLine: '静かな EPUB リーダー。ブックはこのデバイスに保存されます。',
    fonts: 'Literata と OpenDyslexic は SIL Open Font License のもとで提供されています。',
    privacy:
      'Linen はどこにも何も送信しません。問題が起きた場合、詳細はこの Mac のクラッシュログに書き込まれます。必要に応じてメールに添付できます。',
    showCrashLog: 'クラッシュログを表示',
  },
  extensions: {
    stopped: (name: string) => `${name} が応答しなくなりました`,
    restart: '再起動',
    notResponding: '応答なし',
    restartNamed: (name: string) => `${name} を再起動`,
    manage: '機能拡張を管理…',
    more: '機能拡張のその他のアクション',
    via: (name: string) => `機能拡張「${name}」から`,
    exported: '書き出しました',
    exportFailed: (name: string) => `${name} は書き出せませんでした`,
  },
  extSettings: {
    install: 'ファイルからインストール…',
    builtin: '内蔵',
    themePack: 'テーマパック',
    off: 'オフ',
    canAccess: 'アクセスできるもの',
    adds: '追加するもの',
    can: 'できること',
    nothing: 'なし — テーマにはコードが含まれません',
    noAccess: '自身の保存領域以外にはアクセスしません',
    enabled: (name: string) => `${name} オン`,
    failures: (n: number) => `最近${n}回応答しなくなり、再起動されました。読書には影響ありません。`,
    suspended: '10分間に3回応答しなくなったため、一時停止しました。読書には影響ありません。',
    restart: '再起動',
    disable: '無効にする',
    incompatible: (why: string) => `オフになりました：${why}。`,
    remove: '削除…',
    pin: '⋯ メニューにコマンドを表示',
    restartWithout: '機能拡張なしで再起動',
    shiftHint: 'Linen の起動中に ⇧ を押し続けても利用できます。',
    safeMode: 'Linen は機能拡張なしで起動しました。次回の起動時に元に戻ります。',
    installTitle: (name: string) => `「${name}」をインストールしますか？`,
    updateTitle: (name: string, version: string) =>
      `「${name}」${version} は追加のアクセスを求めています`,
    notVerified:
      'Linen による検証は行われていません。信頼できる人の機能拡張だけをインストールしてください。',
    newAccess: '新しいアクセス',
    cancel: 'キャンセル',
    installButton: 'インストール',
    update: 'アップデート',
    keepCurrent: '現在のバージョンを使い続ける',
    cantInstall: (name: string) => `「${name}」をインストールできません`,
    close: '閉じる',
    installed: (name: string) => `「${name}」をインストールしました`,
    removeTitle: (name: string) => `「${name}」を削除しますか？`,
    removeBody:
      '保存したデータも削除しますか？ 残しておくと、機能拡張を再インストールしたときに戻ります。',
    keepData: 'データを残す',
    deleteData: 'データを削除',
    fileFilter: 'Linen 機能拡張',
    permissions: {
      'book.metadata': 'ブックのタイトルと著者を見る',
      'book.selection': '選択したテキストを読む',
      'book.text': 'ブック全体を読む',
      'annotations.read': 'ハイライトとメモを読む',
      'annotations.write': 'ハイライトとメモを変更する',
      'library.read': 'ライブラリ内のすべてのブックを見る',
      'reading.sessions': 'いつ、どれだけ読んだかを知る',
      'files.import': '選択したファイルを開く',
      'files.export': '選択したファイルに保存する',
      background: 'バックグラウンドで実行する',
    },
    connect: (host: string) => `${host} に接続`,
    connectAny: (suffix: string) => `${suffix} で終わる任意のアドレスに接続`,
    commandsAdded: (n: number) => `${n}個のコマンド`,
    inSelectionMenu: (title: string) => `選択メニューの「${title}」`,
    navigatorTab: 'ナビゲータのタブ',
    themesAdded: (n: number) => `${n}個のテーマ`,
    exportInNotes: 'メモからの書き出し',
  },
  info: {
    label: 'ブック情報',
    done: '完了',
    by: '著者',
    publisher: '出版社',
    published: '発行日',
    language: '言語',
    identifier: '識別子',
    added: '追加日',
    fileSize: 'ファイルサイズ',
    layout: 'レイアウト',
    fixed: '固定レイアウト',
    reflowable: 'リフロー',
    accessibility: 'アクセシビリティ',
    noAccessibility: 'このブックにはアクセシビリティ情報がありません。',
    description: '説明',
    sizeMB: (n: string) => `${n} MB`,
    sizeKB: (n: string) => `${n} KB`,
    a11y: {
      accessMode: {
        textual: 'テキストとして読める',
        visual: '視覚的なコンテンツを含む',
        auditory: 'オーディオコンテンツを含む',
      },
      accessModeSufficient: {
        textual: 'すべてテキストとして読める',
        visual: '一部のコンテンツは視覚が必要',
      },
      accessibilityFeature: {
        alternativeText: '画像に代替テキストあり',
        longDescription: '複雑な画像に詳しい説明あり',
        tableOfContents: '目次あり',
        readingOrder: '論理的な読み順あり',
        structuralNavigation: 'ナビゲーション用の見出しあり',
        pageBreakMarkers: '紙の本のページを示す',
        printPageNumbers: '紙の本のページを示す',
        MathML: '数式を MathML で記述',
        displayTransformability: 'テキストのスタイルを変更可能',
        synchronizedAudioText: '読み上げ音声あり',
        ARIA: 'ARIA ロールを使用',
        index: '索引あり',
        captions: 'キャプションあり',
      },
      accessibilityHazard: {
        none: '既知の危険なし',
        noFlashingHazard: '点滅の危険なし',
        noMotionSimulationHazard: '動きの危険なし',
        noSoundHazard: '音の危険なし',
        flashing: '警告：点滅するコンテンツ',
        motionSimulation: '警告：動きのシミュレーション',
        sound: '警告：音',
        unknown: '危険性は不明',
      },
    },
  },
  update: {
    ready: (version: string) => `アップデートの準備ができました · Linen ${version}`,
    restart: '再起動',
    available: (version: string) => `Linen ${version} が利用可能です`,
    download: 'ダウンロード',
  },
  import: {
    addedDamaged: (title: string, n: number) => `「${title}」を追加しました · ${n}章が破損`,
    alreadyInLibrary: (path: string) => `「${fileName(path)}」はすでにライブラリにあります`,
    replaced: (title: string) => `「${title}」を新しいファイルからアップデートしました`,
    drm: (path: string) => `「${fileName(path)}」は DRM で保護されているため、Linen では開けません`,
    hostile: (path: string) => `「${fileName(path)}」は安全に開けないため、追加されませんでした`,
    rejected: (path: string, reason: string) =>
      `「${fileName(path)}」を開けませんでした · ${reason}`,
    fileFilter: 'EPUB',
    reasons: {
      not_zip: 'zip アーカイブでないか、アーカイブが途中で切れています',
      too_many_entries: (max: string) => `項目が${max}個を超えています`,
      too_large: '展開後のサイズが 1 GB を超えています',
      compression_ratio: (entry: string, ratio: string) =>
        `項目 ${entry} の圧縮率が ${ratio}:1 を超えています`,
      unsafe_path: (entry: string) => `安全でない項目パス ${entry}`,
      symlink: (entry: string) => `シンボリックリンクの項目 ${entry}`,
      no_package: 'container.xml またはパッケージ文書がありません',
      bad_package: 'パッケージ文書が整形式の XML ではありません',
      xml_entities: (entry: string) => `${entry} が XML エンティティを宣言しています`,
      drm: (entry: string) => `${entry} に暗号化されたコンテンツ（DRM）があります`,
      no_chapters: 'このブックの章を1つも開けませんでした',
    },
  },
  reader: {
    simplified: 'このブックのスタイルを簡素化しました',
    unsimplified: 'このブック本来のスタイルに戻しました',
    undo: '取り消す',
    library: 'ライブラリ',
    more: 'その他',
    caretOn:
      'キャレットブラウズがオンです。矢印キーでキャレットを移動し、Shift と矢印キーで選択します。',
    caretOff: 'キャレットブラウズがオフです',
    contents: '目次',
    previousPage: '前のページ',
    nextPage: '次のページ',
    minutesLeft: (n: number) => `この章の残り${n}分`,
    resumedIn: (chapter: string) => `${chapter}から再開しました`,
    resumed: '前回の続きから再開しました',
    goToBeginning: '最初に移動',
    backToPage: (page: string) => `${page}ページに戻る`,
    back: '戻る',
    pageAnnouncement: (page: number) => `${page}ページ`,
    pageAnnouncementApprox: (page: number) => `約${page}ページ`,
    approxPage: (page: number) => `≈${page}`,
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `${pages[0]}–${pages[pages.length - 1]} / ${total}ページ`
        : `${pages[0]} / ${total}ページ`,
    zoomLevel: (zoom: number) => formatPercent(zoom),
    zoomFit: 'フィット',
    opening: (title: string) => `「${title}」を開いています…`,
  },
  search: {
    label: 'ブック内を検索',
    placeholder: 'ブック内を検索',
    clear: '検索を消去',
    count: (n: number, chapters: number) => `${chapters}章で${n}件`,
    soFar: '（検索中）',
    searching: (n: number, of: number) => `${of}章中${n}章を検索中`,
    showAll: (n: number) => `${n}件すべてを表示`,
    none: (q: string) => `「${q}」に一致する結果はありません`,
    options: '検索オプション',
    wholeWords: '単語単位',
    regex: '正規表現',
    invalid: 'この正規表現は無効です。',
    next: '次へ',
    previous: '前へ',
    back: 'ページに戻る',
    result: (i: number, n: number, chapter: string) =>
      [`${n}件中${i}件目`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: 'ナビゲータ',
    tabs: 'ナビゲータのセクション',
    search: '検索',
    notes: 'メモ',
    more: 'その他',
    close: 'ナビゲータを閉じる',
    contents: '目次',
    loading: '目次を読み込んでいます…',
    generated: '見出しから生成',
    youAreHere: '現在の位置',
    damaged: '破損',
  },
  aa: {
    label: '読書設定',
    button: '読書設定',
    textSize: '文字サイズ',
    sizeScope: (px: number) => `${px} px · すべてのブック`,
    px: (px: number) => `${px}ピクセル`,
    theme: 'テーマ',
    paper: 'ペーパー',
    sepia: 'セピア',
    night: 'ナイト',
    auto: '自動',
    lineSpacing: '行間',
    compact: '狭い',
    normal: '標準',
    loose: '広い',
    layout: 'レイアウト',
    pages: 'ページ',
    scroll: 'スクロール',
    allBooks: 'すべてのブック',
    thisBook: 'このブック',
    moreSettings: '詳細は設定で…',
    anywhere: '⌘+ ⌘− はどこでも使えます',
    codeHint: 'このブックの多くはコードや表です。スクロールの方が読みやすいかもしれません。',
    fixedLayout:
      'このブックは固定レイアウトのため、文字サイズと間隔は変更できません。⌘+ と ⌘− でページを拡大・縮小できます。',
    font: 'フォント',
    fontBook: 'ブック',
    fontLiterata: 'Literata',
    fontSans: 'サンセリフ',
    fontDyslexic: 'ディスレクシア',
    fontDyslexicLong: 'OpenDyslexic',
    width: 'ページの幅',
    narrow: '狭い',
    wide: '広い',
  },
  annotations: {
    bar: '選択範囲のアクション',
    barAnnounce: '選択範囲のアクション、F6',
    highlightIn: (color: string, lastUsed: boolean) =>
      `${color}でハイライト${lastUsed ? '、最後に使用（H または ⇧⌘H）' : ''}`,
    colorOption: (color: string, current: boolean) => `${color}${current ? '、現在の色' : ''}`,
    note: 'メモ',
    copy: 'コピー',
    search: '検索',
    delete: '削除',
    copied: 'コピーしました',
    highlighted: (color: string) => `${color}でハイライトしました`,
    deleted: 'ハイライトを削除しました',
    noteDeleted: 'メモを削除しました',
    recolored: (color: string) => `ハイライトを${color}に変更しました`,
    highlightCommand: (color: string) => `${color}でハイライト`,
    undo: '取り消す',
    restore: (quote: string) => `ハイライト「${quote}」を元に戻す`,
    restoreNote: (quote: string) => `「${quote}」のメモを元に戻す`,
    restoreColor: (quote: string) => `「${quote}」の色を元に戻す`,
    noteTitle: (color: string) => `メモ · ${color}`,
    noteLabel: 'ハイライトのメモ',
    noteText: 'メモのテキスト',
    saving: '保存中…',
    saved: '保存しました',
    notSaved: 'まだ保存されていません',
    noteHint: '入力すると保存されます · Esc で閉じるとテキストにフォーカスが戻ります',
    copyNote: '引用とメモをコピー',
    deleteNote: 'ハイライトとメモを削除',
    done: '完了',
    filter: 'ハイライトとメモを絞り込む',
    all: 'すべて',
    only: (color: string) => `${color}のみ`,
    counts: (h: number, n: number) => `ハイライト${h}件 · メモ${n}件`,
    today: '今日',
    yesterday: '昨日',
    hasNote: 'メモ',
    none: 'ハイライトはまだありません。テキストを選択して色を選ぶか、H を押してください。',
    noMatches: '一致するハイライトはありません。',
    couldntPlace: '配置できません',
    changedReason: 'これを保存したあとにブックのファイルが変更されました。',
    reattach: '再配置',
    reattachPrompt: (quote: string) => `「${quote}」の箇所を選択してください`,
    attachHere: 'ここに配置',
    cancel: 'キャンセル',
    reattached: 'ハイライトを再配置しました',
    unplacedAfterUpdate: (n: number) =>
      `${n}件のハイライトをアップデート後のブックに配置できませんでした`,
    show: '表示',
  },
  colors: { yellow: '黄色', green: '緑', blue: '青', rose: 'ローズ' },
  colorsInText: { yellow: '黄色', green: '緑', blue: '青', rose: 'ローズ' },
  goto: {
    label: '場所へ移動',
    percent: 'パーセント',
    chapter: '章',
    page: '紙の本のページ',
    percentLabel: 'ブック内のパーセント',
    chapterLabel: '章',
    pageLabel: '紙の本のページ',
    go: '移動',
    stays: '現在の場所は「戻る」の履歴に残ります（⌘[）。',
    percentIn: (pct: number) => `${formatPercent(pct / 100)} の位置は `,
    pageIn: (page: string) => `${page}ページは `,
    chapterAt: (pct: number) => ` は ${formatPercent(pct / 100)} から始まります。`,
    sentenceEnd: 'にあります。',
    noPage: (page: string) => `このブックに${page}ページはありません。`,
    pageListOnly: '紙の本のページは、ブックにページリストがある場合にのみ利用できます。',
    open: '移動…',
    scrubber: 'ブック内の位置',
  },
  peek: {
    label: (n: string) => `注 ${n}`,
    title: (n: string) => `注 ${n}`,
    hint: 'Esc で閉じる · マーカーにフォーカスが戻ります',
    openInPlace: '注をその場所で開く',
    copy: 'コピー',
    copied: '注をコピーしました',
    missing: 'この注はブック内に見つかりませんでした。',
  },
  shortcuts: {
    intro:
      'どのコマンドにも、機能拡張のコマンドにもショートカットを割り当てられます。ショートカットには ⌘、⌃、⌥ のいずれかが必要です（ファンクションキーは単独で使えます）。機能拡張は Linen 自身のショートカットを使えません。',
    none: 'なし',
    change: '変更',
    cancel: 'キャンセル',
    remove: '削除',
    reset: 'リセット',
    resetAll: 'すべてのショートカットをリセット',
    typeNow: 'ショートカットを入力…',
    changeFor: (title: string) => `「${title}」のショートカットを変更`,
    removeFor: (title: string) => `「${title}」のショートカットを削除`,
    resetFor: (title: string) => `「${title}」のショートカットをリセット`,
    needsModifier:
      'ショートカットには ⌘、⌃、⌥ のいずれかが必要です（ファンクションキーは単独で使えます）。',
    reserved: (keys: string) => `${keys} は macOS または Linen が使用しているため変更できません。`,
    taken: (keys: string, title: string) =>
      `${keys} は Linen の「${title}」のショートカットです。機能拡張では使えません。`,
    moved: (keys: string, title: string) => `${keys} では「${title}」が実行されなくなりました。`,
  },
  lookUp: {
    action: '調べる',
    label: (word: string) => `${word}の定義`,
    title: '辞書',
    hint: 'Esc で閉じる',
    looking: '調べています…',
    none: (word: string) => `この Mac の辞書に「${word}」はありません。`,
    openDictionary: '辞書で開く',
    searchBook: 'ブックを検索',
    contextMenu: (word: string) =>
      `「${word.length > 24 ? word.slice(0, 23) + '…' : word}」を調べる`,
  },
  image: {
    label: '画像',
    close: '画像を閉じる',
    zoomIn: '拡大',
    zoomOut: '縮小',
    fit: 'フィット',
  },
  cheatSheet: {
    title: 'キーボードショートカット',
    close: '閉じる',
    singleKeys:
      '単一キーのショートカット（[ や ] など）は、ブックのテキストにフォーカスがあり、スクリーンリーダーが動作していないときに使えます。',
    pages: 'ページ',
    sections: {
      navigation: 'ナビゲーション',
      reading: '読書',
      search: '検索',
      annotation: 'ハイライトとメモ',
      view: '表示',
      app: 'アプリ',
      extension: '機能拡張',
    },
    nextPage: '次のページ',
    previousPage: '前のページ',
    scrollScreen: '1画面ずつスクロール（スクロールモード）',
    scrollLines: '1行ずつスクロール（スクロールモード）',
  },
  keys: { esc: 'Esc', space: 'スペース', pageUp: 'PgUp', pageDown: 'PgDn' },
  menus: {
    file: 'ファイル',
    edit: '編集',
    view: '表示',
    go: '移動',
    window: 'ウインドウ',
    about: (app: string) => `${app} について`,
    services: 'サービス',
    hide: (app: string) => `${app} を非表示`,
    hideOthers: 'ほかを非表示',
    showAll: 'すべてを表示',
    quit: (app: string) => `${app} を終了`,
    cut: 'カット',
    copy: 'コピー',
    paste: 'ペースト',
    selectAll: 'すべてを選択',
    minimize: 'しまう',
  },
  palette: {
    label: 'コマンドパレット',
    placeholder: 'コマンド、章、設定を入力',
    recentlyClosed: '最近閉じたもの',
    reading: '読書',
    chapters: '章',
    none: '一致するコマンドはありません',
    move: '移動',
    run: '実行',
    all: 'すべてのショートカット',
  },
  messages: {
    region: 'メッセージ',
    dismiss: '閉じる',
    saveFailed: 'メモをディスクに保存できませんでした',
    retry: '再試行',
    quitUnsaved: '保存されていないメモがあるため、Linen は終了しませんでした',
    quitAnyway: 'このまま終了',
  },
  commands: {
    'chapter.next': '次の章',
    'chapter.previous': '前の章',
    'search.open': 'ブック内を検索',
    'search.next': '次の結果',
    'search.previous': '前の結果',
    'navigator.contents': '章へ移動…',
    'goto.open': '場所へ移動…',
    'navigator.notes': 'ハイライトとメモ',
    'selection.highlight': '選択範囲をハイライト',
    'selection.note': '選択範囲にメモを追加',
    'selection.focusBar': '選択範囲のアクションへ移動',
    'reader.caretBrowsing': 'キャレットブラウズ',
    'text.larger': '文字を大きく',
    'text.smaller': '文字を小さく',
    'text.reset': 'デフォルトの文字サイズ',
    'layout.pages': 'ページモード',
    'layout.scroll': 'スクロールモード',
    'reader.settings': '読書設定…',
    'reader.simplifyStyles': 'このブックのスタイルを簡素化',
    'selection.lookUp': '選択範囲を調べる',
    'app.settings': '設定…',
    'palette.open': 'コマンドパレット',
    'shortcuts.show': 'キーボードショートカット',
    'history.back': '戻る',
    'library.show': 'ライブラリ',
    'book.open': '開く…',
    'window.fullScreen': 'フルスクリーン',
    'edit.undo': '取り消す',
    'layer.close': 'レイヤーを閉じる',
  },
}
