// The Traditional Chinese catalogue, Taiwan usage (L-1, L-2). A machine draft
// (2026-10-07, L-6): it follows docs/i18n/style.md and docs/i18n/glossary.md and
// waits for a native speaker's review in context before it ships. Keys, values
// and context: en.ts.

import { formatPercent } from './format'
import type { Messages } from './types'

const fileName = (path: string) => path.split('/').pop() ?? path

export const zhHant: Messages = {
  library: {
    emptyTitle: '你的書庫是空的',
    emptyBody: '將 EPUB 檔案拖到這裡，或從電腦中打開一本。',
    openBook: '打開一本書…',
    open: '打開…',
    note: '書籍會拷貝到你的書庫，並保留在這部裝置上。',
    title: '書庫',
    count: (n: number) => `${n} 本書`,
    unknownAuthor: '未知作者',
    damaged: (n: number) => `${n} 本已損毀`,
    new: '新',
    finished: '已讀完',
    percent: (fraction: number) => formatPercent(fraction),
    search: '搜尋書庫',
    searchPlaceholder: '搜尋書名或作者',
    sortBy: (label: string) => `排序方式：${label}`,
    sorts: { recent: '最近', title: '書名', author: '作者' },
    view: '顯示方式',
    viewGrid: '封面',
    viewList: '列表',
    neverOpened: '—',
    continueReading: '繼續閱讀',
    openedAt: (day: string, time: string) => `${day} ${time} 打開`,
    openedAgo: (ago: string) => `${ago}打開`,
    allBooks: '所有書籍',
    resume: '繼續閱讀',
    itemMenu: (title: string) => `「${title}」的更多操作`,
    info: '書籍資訊',
    showFile: '在 Finder 中顯示',
    remove: '移除',
    removed: (title: string) => `已移除「${title}」`,
    restore: (title: string) => `復原「${title}」`,
    noMatches: (q: string) => `沒有符合「${q}」的書籍`,
    damagedTitle: '這本書有一部分無法打開',
    damagedBody: (n: number, total: number) =>
      `${total ? `${total} 個章節中有 ${n} 個` : `${n} 個章節`}已損毀。你可以閱讀其餘部分；損毀的章節會在目錄中標出，不會無聲無息地缺漏。`,
    damagedFile: (title: string, size: string) => `${title} · ${size}`,
    readAnyway: '仍要閱讀',
    showFileShort: '顯示檔案',
    clear: '清除',
    webkitTitle: '閱讀書籍需要較新版本的 Safari',
    webkitBody:
      'Linen 使用 Mac 內建的網頁引擎來顯示書籍，它隨 Safari 一起提供。這部 Mac 上的版本低於 Linen 所需的 Safari 16.4 或以上版本。請在「軟體更新」中更新，然後再次打開這本書。你的書庫和筆記都很安全。',
    webkitUpdate: '打開「軟體更新」',
    webkitClose: '稍後',
  },
  prefs: {
    title: '設定',
    sections: {
      general: '一般',
      reading: '閱讀',
      library: '書庫',
      dictionaries: '辭典',
      extensions: '延伸功能',
      shortcuts: '快速鍵',
      about: '關於',
    },
    theme: '主題',
    atLaunch: 'Linen 打開時',
    atLaunchLibrary: '顯示書庫',
    atLaunchBook: '重新打開上次的書',
    language: '語言',
    languageSystem: (name: string) => `系統（${name}）`,
    languageRestart: 'Linen 重新啟動後會使用新語言。',
    restartNow: '立即重新啟動',
    textSize: '文字大小',
    lineSpacing: '行距',
    font: '字體',
    pageWidth: '頁面寬度',
    publisherStyles: '出版社樣式',
    publisherFull: '完整',
    publisherBalanced: '平衡',
    publisherOff: '關閉',
    publisherHelp:
      '「平衡」保留書籍的設計，但行距和對齊方式由你決定。「完整」保留全部樣式；「關閉」顯示純文字。也可以從單本書的 ⋯ 選單中簡化它的樣式。',
    crossfade: '翻頁淡入淡出',
    crossfadeHelp: '翻頁時頁面在 120 毫秒內相互淡入，而不是立即切換。',
    announcements: '朗讀翻頁',
    announcementsHelp: '每次翻頁後，螢幕閱讀器會讀出「第 N 頁」。',
    folder: '書庫資料夾',
    folderHelp:
      '你的書籍、封面、螢光標示和筆記都在這個資料夾中。備份它即可保留這些內容；Time Machine 會自動備份。',
    showFolder: '在 Finder 中顯示',
    exportAll: '輸出所有螢光標示和筆記…',
    exportHelp: '每本書一個 W3C Web Annotation 檔案，其他 App 也能讀取。',
    exported: (n: number) => `已輸出 ${n} 本書`,
    nothingToExport: '沒有可輸出的螢光標示。',
    uninstall:
      '從「應用程式」中移除 Linen 後，這個資料夾仍會保留。若要同時移除書庫，請將它一併刪除。',
    extensionsIntro:
      '延伸功能會在固定的位置加入動作、面板、主題和輸出工具。它們不能改變頁面的外觀，未經你允許也不能讀取你的書籍或筆記。',
    extensionsNone: '延伸功能將在之後的版本中提供。',
    singleKeys: '單鍵快速鍵',
    singleKeysHelp: '[ ] H N 等按鍵在文字取得焦點時可用。螢幕閱讀器執行時會自動關閉。',
    showShortcuts: '顯示所有快速鍵',
    version: (v: string) => `版本 ${v}`,
    aboutLine: '一款安靜的 EPUB 閱讀器。你的書籍保留在這部裝置上。',
    fonts: 'Literata 和 OpenDyslexic 依據 SIL Open Font License 授權。',
    privacy:
      'Linen 不會向任何地方傳送任何內容。如果發生問題，詳細資訊會寫入這部 Mac 上的當機記錄，你可以自行選擇是否附加到電子郵件中。',
    showCrashLog: '顯示當機記錄',
  },
  extensions: {
    stopped: (name: string) => `${name} 已停止回應`,
    restart: '重新啟動',
    notResponding: '沒有回應',
    restartNamed: (name: string) => `重新啟動 ${name}`,
    manage: '管理延伸功能…',
    more: '延伸功能提供的更多動作',
    via: (name: string) => `來自延伸功能「${name}」`,
    exported: '已輸出',
    exportFailed: (name: string) => `${name} 無法輸出`,
  },
  extSettings: {
    install: '從檔案安裝…',
    builtin: '內建',
    themePack: '主題包',
    off: '關閉',
    canAccess: '可取用',
    adds: '加入',
    can: '可以',
    nothing: '無 — 主題不含程式碼',
    noAccess: '僅限其自身的儲存空間',
    enabled: (name: string) => `${name} 已開啟`,
    failures: (n: number) => `最近停止回應 ${n} 次並已重新啟動。閱讀未受影響。`,
    suspended: '十分鐘內三次停止回應，已暫停。閱讀未受影響。',
    restart: '重新啟動',
    disable: '停用',
    incompatible: (why: string) => `已關閉：${why}。`,
    remove: '移除…',
    pin: '在 ⋯ 選單中顯示其指令',
    restartWithout: '不使用延伸功能重新啟動',
    shiftHint: '也可以在 Linen 打開時按住 ⇧。',
    safeMode: 'Linen 已在不使用延伸功能的情況下啟動。下次打開時延伸功能會恢復。',
    installTitle: (name: string) => `要安裝「${name}」嗎？`,
    updateTitle: (name: string, version: string) => `「${name}」${version} 需要更多權限`,
    notVerified: '未經 Linen 驗證。請只安裝你信任的人提供的延伸功能。',
    newAccess: '新的權限',
    cancel: '取消',
    installButton: '安裝',
    update: '更新',
    keepCurrent: '保留目前版本',
    cantInstall: (name: string) => `無法安裝「${name}」`,
    close: '關閉',
    installed: (name: string) => `已安裝「${name}」`,
    removeTitle: (name: string) => `要移除「${name}」嗎？`,
    removeBody: '同時刪除它儲存的內容嗎？如果保留，重新安裝該延伸功能時這些內容會回來。',
    keepData: '保留其資料',
    deleteData: '刪除其資料',
    fileFilter: 'Linen 延伸功能',
    permissions: {
      'book.metadata': '查看書籍的書名和作者',
      'book.selection': '讀取你選取的文字',
      'book.text': '讀取整本書',
      'annotations.read': '讀取螢光標示和筆記',
      'annotations.write': '更改螢光標示和筆記',
      'library.read': '查看書庫中的每一本書',
      'reading.sessions': '了解你何時閱讀以及閱讀多久',
      'files.import': '打開你選擇的檔案',
      'files.export': '儲存到你選擇的檔案',
      background: '在背景執行',
    },
    connect: (host: string) => `連線到 ${host}`,
    connectAny: (suffix: string) => `連線到任何以 ${suffix} 結尾的位址`,
    commandsAdded: (n: number) => `${n} 個指令`,
    inSelectionMenu: (title: string) => `選取選單中的「${title}」`,
    inLookupMenu: (title: string) => `查詢視窗中的「${title}」`,
    navigatorTab: '導覽列標籤頁',
    themesAdded: (n: number) => `${n} 個主題`,
    exportInNotes: '在筆記中輸出',
  },
  info: {
    label: '書籍資訊',
    done: '完成',
    by: '作者',
    publisher: '出版社',
    published: '出版日期',
    language: '語言',
    identifier: '識別碼',
    added: '加入日期',
    fileSize: '檔案大小',
    layout: '版面',
    fixed: '固定版面',
    reflowable: '可重排',
    accessibility: '輔助使用',
    noAccessibility: '這本書未提供輔助使用資訊。',
    description: '簡介',
    sizeMB: (n: string) => `${n} MB`,
    sizeKB: (n: string) => `${n} KB`,
    a11y: {
      accessMode: {
        textual: '可作為文字閱讀',
        visual: '包含視覺內容',
        auditory: '包含音訊內容',
      },
      accessModeSufficient: {
        textual: '可完全作為文字閱讀',
        visual: '部分內容需要視覺',
      },
      accessibilityFeature: {
        alternativeText: '影像有替代文字',
        longDescription: '複雜影像有詳細描述',
        tableOfContents: '有目錄',
        readingOrder: '有合理的閱讀順序',
        structuralNavigation: '有用於導覽的標題',
        pageBreakMarkers: '標出紙本頁碼',
        printPageNumbers: '標出紙本頁碼',
        MathML: '以 MathML 呈現數學內容',
        displayTransformability: '文字樣式可調整',
        synchronizedAudioText: '有朗讀音訊',
        ARIA: '使用 ARIA 角色',
        index: '有索引',
        captions: '有字幕',
      },
      accessibilityHazard: {
        none: '無已知危險',
        noFlashingHazard: '無閃爍危險',
        noMotionSimulationHazard: '無動態危險',
        noSoundHazard: '無聲音危險',
        flashing: '警告：閃爍內容',
        motionSimulation: '警告：動態模擬',
        sound: '警告：聲音',
        unknown: '危險未知',
      },
    },
  },
  update: {
    ready: (version: string) => `更新已就緒 · Linen ${version}`,
    restart: '重新啟動',
    available: (version: string) => `Linen ${version} 現已推出`,
    download: '下載',
  },
  import: {
    addedDamaged: (title: string, n: number) => `已加入「${title}」 · ${n} 個章節已損毀`,
    alreadyInLibrary: (path: string) => `「${fileName(path)}」已在你的書庫中`,
    replaced: (title: string) => `已用較新的檔案更新「${title}」`,
    drm: (path: string) => `「${fileName(path)}」受 DRM 保護，無法在 Linen 中打開`,
    hostile: (path: string) => `「${fileName(path)}」無法安全打開，未加入`,
    rejected: (path: string, reason: string) => `無法打開「${fileName(path)}」 · ${reason}`,
    fileFilter: 'EPUB',
    reasons: {
      not_zip: '不是 zip 封存檔，或封存檔已截斷',
      too_many_entries: (max: string) => `項目超過 ${max} 個`,
      too_large: '解壓縮後大小超過 1 GB',
      compression_ratio: (entry: string, ratio: string) => `項目 ${entry} 的壓縮比超過 ${ratio}:1`,
      unsafe_path: (entry: string) => `不安全的項目路徑 ${entry}`,
      symlink: (entry: string) => `符號連結項目 ${entry}`,
      no_package: '沒有 container.xml 或套件文件',
      bad_package: '套件文件不是格式正確的 XML',
      xml_entities: (entry: string) => `${entry} 宣告了 XML 實體`,
      drm: (entry: string) => `${entry} 中有加密內容（DRM）`,
      no_chapters: '這本書的章節都無法打開',
    },
  },
  reader: {
    simplified: '已簡化這本書的樣式',
    unsimplified: '已恢復這本書自己的樣式',
    undo: '還原',
    library: '書庫',
    more: '更多',
    caretOn: '游標瀏覽已開啟。方向鍵移動游標；Shift 加方向鍵進行選取。',
    caretOff: '游標瀏覽已關閉',
    contents: '目錄',
    previousPage: '上一頁',
    nextPage: '下一頁',
    minutesLeft: (n: number) => `本章還剩 ${n} 分鐘`,
    resumedIn: (chapter: string) => `已從 ${chapter} 繼續`,
    resumed: '已從上次的位置繼續',
    goToBeginning: '前往開頭',
    backToPage: (page: string) => `返回第 ${page} 頁`,
    back: '返回',
    pageAnnouncement: (page: number) => `第 ${page} 頁`,
    pageAnnouncementApprox: (page: number) => `約第 ${page} 頁`,
    approxPage: (page: number) => `≈${page}`,
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `第 ${pages[0]}–${pages[pages.length - 1]} 頁，共 ${total} 頁`
        : `第 ${pages[0]} 頁，共 ${total} 頁`,
    zoomLevel: (zoom: number) => formatPercent(zoom),
    zoomFit: '符合大小',
    opening: (title: string) => `正在打開「${title}」…`,
  },
  search: {
    label: '在書中搜尋',
    placeholder: '在書中搜尋',
    clear: '清除搜尋',
    count: (n: number, chapters: number) => `在 ${chapters} 個章節中找到 ${n} 個結果`,
    soFar: '（搜尋中）',
    searching: (n: number, of: number) => `正在搜尋第 ${n} 章，共 ${of} 章`,
    showAll: (n: number) => `顯示全部 ${n} 個`,
    none: (q: string) => `沒有「${q}」的結果`,
    options: '搜尋選項',
    wholeWords: '全字相符',
    regex: '正規表示式',
    invalid: '這個正規表示式無效。',
    next: '下一個',
    previous: '上一個',
    back: '返回你的頁面',
    result: (i: number, n: number, chapter: string) =>
      [`第 ${i} 個結果，共 ${n} 個`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: '導覽列',
    tabs: '導覽列區段',
    search: '搜尋',
    notes: '筆記',
    more: '更多',
    close: '關閉導覽列',
    contents: '目錄',
    loading: '正在讀取目錄…',
    generated: '依標題產生',
    youAreHere: '你在這裡',
    damaged: '已損毀',
  },
  aa: {
    label: '閱讀設定',
    button: '閱讀設定',
    textSize: '文字大小',
    sizeScope: (px: number) => `${px} px · 所有書籍`,
    px: (px: number) => `${px} 像素`,
    theme: '主題',
    paper: '紙張',
    sepia: '棕褐',
    night: '夜間',
    auto: '自動',
    lineSpacing: '行距',
    compact: '緊密',
    normal: '正常',
    loose: '寬鬆',
    layout: '版面',
    pages: '翻頁',
    scroll: '捲動',
    allBooks: '所有書籍',
    thisBook: '這本書',
    moreSettings: '更多設定…',
    anywhere: '⌘+ ⌘− 在任何地方都可用',
    codeHint: '這本書大部分是程式碼或表格。捲動模式可能更易閱讀。',
    fixedLayout: '這本書是固定版面，文字大小和間距無法更改。按 ⌘+ 和 ⌘− 縮放頁面。',
    font: '字體',
    fontBook: '書籍',
    fontLiterata: 'Literata',
    fontSans: '無襯線',
    fontDyslexic: '讀寫障礙',
    fontDyslexicLong: 'OpenDyslexic',
    width: '頁面寬度',
    narrow: '窄',
    wide: '寬',
  },
  annotations: {
    bar: '選取動作',
    barAnnounce: '選取動作，F6',
    highlightIn: (color: string, lastUsed: boolean) =>
      `以${color}螢光標示${lastUsed ? '，上次使用（H 或 ⇧⌘H）' : ''}`,
    colorOption: (color: string, current: boolean) => `${color}${current ? '，目前' : ''}`,
    note: '筆記',
    copy: '拷貝',
    search: '搜尋',
    delete: '刪除',
    copied: '已拷貝',
    highlighted: (color: string) => `已以${color}螢光標示`,
    deleted: '已刪除螢光標示',
    noteDeleted: '已刪除筆記',
    recolored: (color: string) => `螢光標示已改為${color}`,
    highlightCommand: (color: string) => `以${color}螢光標示`,
    undo: '還原',
    restore: (quote: string) => `復原螢光標示「${quote}」`,
    restoreNote: (quote: string) => `復原「${quote}」上的筆記`,
    restoreColor: (quote: string) => `復原「${quote}」的顏色`,
    noteTitle: (color: string) => `筆記 · ${color}`,
    noteLabel: '螢光標示上的筆記',
    noteText: '筆記文字',
    saving: '正在儲存…',
    saved: '已儲存',
    notSaved: '尚未儲存',
    noteHint: '輸入時自動儲存 · 按 Esc 關閉，焦點回到文字',
    copyNote: '拷貝引文和筆記',
    deleteNote: '刪除螢光標示和筆記',
    done: '完成',
    filter: '過濾螢光標示和筆記',
    all: '全部',
    only: (color: string) => `僅${color}`,
    counts: (h: number, n: number) => `${h} 個螢光標示 · ${n} 則筆記`,
    today: '今天',
    yesterday: '昨天',
    hasNote: '筆記',
    none: '還沒有螢光標示。選取文字並選擇一種顏色，或按 H。',
    noMatches: '沒有符合的螢光標示。',
    couldntPlace: '無法定位',
    changedReason: '儲存之後書籍檔案有所變更。',
    reattach: '重新附加',
    reattachPrompt: (quote: string) => `選取「${quote}」所在的段落`,
    attachHere: '附加到這裡',
    cancel: '取消',
    reattached: '已重新附加螢光標示',
    unplacedAfterUpdate: (n: number) => `有 ${n} 個螢光標示無法在更新後的書籍中定位`,
    show: '顯示',
  },
  colors: { yellow: '黃色', green: '綠色', blue: '藍色', rose: '玫瑰色' },
  colorsInText: { yellow: '黃色', green: '綠色', blue: '藍色', rose: '玫瑰色' },
  goto: {
    label: '前往位置',
    percent: '百分比',
    chapter: '章節',
    page: '紙本頁碼',
    percentLabel: '書籍的百分比',
    chapterLabel: '章節',
    pageLabel: '紙本頁碼',
    go: '前往',
    stays: '你目前的位置會保留在返回記錄中（⌘[）。',
    percentIn: (pct: number) => `${formatPercent(pct / 100)} 位於 `,
    pageIn: (page: string) => `第 ${page} 頁位於 `,
    chapterAt: (pct: number) => ` 從 ${formatPercent(pct / 100)} 開始。`,
    sentenceEnd: '。',
    noPage: (page: string) => `這本書中沒有第 ${page} 頁。`,
    pageListOnly: '只有在書籍包含頁碼列表時才能使用紙本頁碼。',
    open: '前往…',
    scrubber: '在書中的位置',
  },
  peek: {
    label: (n: string) => `註釋 ${n}`,
    title: (n: string) => `註釋 ${n}`,
    hint: '按 Esc 關閉 · 焦點回到標記',
    openInPlace: '在原位置打開註釋',
    copy: '拷貝',
    copied: '已拷貝註釋',
    missing: '在書中找不到這則註釋。',
  },
  shortcuts: {
    intro:
      '可以為任何指令設定快速鍵，包括延伸功能提供的指令。快速鍵需要使用 ⌘、⌃ 或 ⌥（功能鍵可單獨使用）；延伸功能不能佔用 Linen 自己的快速鍵。',
    none: '無',
    change: '更改',
    cancel: '取消',
    remove: '移除',
    reset: '重置',
    resetAll: '重置所有快速鍵',
    typeNow: '輸入快速鍵…',
    changeFor: (title: string) => `更改「${title}」的快速鍵`,
    removeFor: (title: string) => `移除「${title}」的快速鍵`,
    resetFor: (title: string) => `重置「${title}」的快速鍵`,
    needsModifier: '快速鍵需要使用 ⌘、⌃ 或 ⌥（功能鍵可單獨使用）。',
    reserved: (keys: string) => `${keys} 屬於 macOS 或 Linen，無法更改。`,
    taken: (keys: string, title: string) =>
      `${keys} 是 Linen 用於「${title}」的快速鍵；延伸功能不能佔用它。`,
    moved: (keys: string, title: string) => `${keys} 不再執行「${title}」。`,
  },
  lookUp: {
    action: '查詢',
    label: (word: string) => `「${word}」的釋義`,
    title: '辭典',
    hint: '按 Esc 關閉',
    looking: '正在查詢…',
    none: (word: string) => `這部 Mac 上沒有辭典收錄「${word}」。`,
    openDictionary: '在辭典中打開',
    searchBook: '在書中搜尋',
    contextMenu: (word: string) => `查詢「${word.length > 24 ? word.slice(0, 23) + '…' : word}」`,
  },
  // Reading Lens（PROVISIONAL，機器草稿，待審）
  lens: {
    macDictionaries: '這台 Mac 上的辭典',
    labelMacDictionary: '辭典 · 在這台 Mac 上',
    labelAi: (model: string) => `AI 解釋 · ${model}`,
    labelDictionary: (name: string) => `辭典 · ${name}`,
    explanationOf: (word: string) => `「${word}」的解釋`,
    lookUpWord: (word: string) => `查詢「${word}」`,
    lookUpWith: '查詢方式',
    lookUpWithCommand: (title: string) => `用${title}查詢`,
    asking: (name: string) => `正在詢問 ${name}…`,
    copyExplanation: '拷貝解釋',
    copied: '已拷貝解釋',
    more: '更多',
    less: '收合',
    whatWasSent: '傳送了什麼',
    sentBy: (name: string) => `由 ${name} 傳送`,
    back: '返回',
    searchInBook: '在書中搜尋',
    offline: '你已離線。',
    offlineDetail: (name: string) => `${name} 需要網路連線。`,
    timeout: (name: string) => `${name} 未在 10 秒內回答。`,
    unauthorized: (name: string) => `${name} 未接受密鑰。`,
    unauthorizedDetail: '密鑰可能已過期或被撤銷。',
    rateLimited: (name: string) => `${name} 正在限制請求。`,
    rateLimitedDetail: '請一分鐘後再試。',
    unavailable: (name: string) => `${name} 目前無法使用。`,
    badAnswer: (name: string) => `${name} 傳來的回答無法顯示。`,
    stopped: (name: string) => `${name} 停止回應。`,
    stoppedDetail: '閱讀未受影響。',
    continue: '繼續',
    notNow: '以後再說',
    audioUnavailable: '無法播放音訊',
    inContext: (title: string) => `「${title}」結合上下文`,
    noEntry: (word: string) => `你的辭典中沒有「${word}」的詞條。`,
    dictionaryFrame: (title: string) => `「${title}」中的詞條`,
    tryAgain: '再試一次',
    restart: (name: string) => `重新啟動 ${name}`,
  },
  // Reading Lens（PROVISIONAL，機器草稿，待審）
  dictSettings: {
    intro:
      '你加入的辭典會拷貝到資料庫中並留在這台 Mac 上。查詢單字時 Linen 會顯示其中的詞條，絕不會把它們傳送到任何地方。',
    add: '加入辭典…',
    order: '順序決定查詢視窗先顯示哪本辭典。',
    fileFilter: '辭典',
    details: (entries: string, mdd: boolean) =>
      mdd ? `MDX 和 MDD · ${entries} 個詞條` : `MDX · ${entries} 個詞條`,
    on: '開啟',
    remove: '移除',
    removeNamed: (title: string) => `移除「${title}」`,
    moveUp: (title: string) => `上移「${title}」`,
    moveDown: (title: string) => `下移「${title}」`,
    importing: '正在匯入… 匯入完成前仍使用先前的版本。',
    importingNamed: (name: string) => `正在匯入「${name}」`,
    cancel: '取消',
    dismiss: '關閉',
    added: (title: string) => `已加入「${title}」。`,
    alreadyInstalled: (title: string) => `這本辭典已作為「${title}」安裝。`,
    registered: '這本辭典受註冊保護，只能在其來源的 App 中使用，因此 Linen 無法打開。',
    lzo: '這本辭典使用 LZO 壓縮，Linen 無法讀取。',
    encoding: (name: string) => `這本辭典的文字使用 ${name} 編碼，Linen 無法讀取。`,
    damaged: '這本辭典已損壞，Linen 無法打開。',
    tooLarge: '這本辭典的某部分超出了 Linen 允許的大小。',
    changed: '加入過程中檔案發生了變化。請再試一次。',
    notMdx: '這不是 MDX 辭典。',
    failed: '無法加入這本辭典。仍在使用先前的版本。',
    none: '還沒有辭典。',
  },
  // Reading Lens（PROVISIONAL，機器草稿，待審）
  extAccess: {
    hostTitle: (name: string, host: string) => `允許「${name}」連線到 ${host}？`,
    hostBody: (name: string) =>
      `${name} 會把你選擇傳送的內容傳到這個位址。在你使用它之前不會傳送任何內容。`,
    hostPurpose: (name: string) => `${name} 說明：`,
    hostNote: '你可以在「設定 › 延伸功能」中移除此權限。',
    allow: '允許',
    dontAllow: '不允許',
    keyTitle: (host: string) => `${host} 的密鑰`,
    keyMessage: (name: string, host: string) =>
      `儲存在這台 Mac 的鑰匙圈中。${name} 無法讀取它；Linen 只會把它加到傳往 ${host} 的請求中。`,
    save: '儲存',
    cancel: '取消',
    sendsTo: '傳送到',
    sendsWhat: '你選擇傳送的內容',
    removeHost: (host: string) => `移除 ${host}`,
    remove: '移除',
    options: '選項…',
    optionsTitle: (name: string) => `${name} 選項`,
    done: '完成',
    keyUnavailable: (name: string) => `Linen 無法讀取 ${name} 的密鑰。`,
    keyUnavailableDetail: '鑰匙圈可能已鎖定，或存取遭拒。未傳送任何內容。',
    openOptions: '打開選項',
  },
  image: {
    label: '影像',
    close: '關閉影像',
    zoomIn: '放大',
    zoomOut: '縮小',
    fit: '符合大小',
  },
  cheatSheet: {
    title: '鍵盤快速鍵',
    close: '關閉',
    singleKeys: '單鍵快速鍵（例如 [ 和 ]）在書中文字取得焦點且沒有執行螢幕閱讀器時可用。',
    pages: '翻頁',
    sections: {
      navigation: '導覽',
      reading: '閱讀',
      search: '搜尋',
      annotation: '螢光標示與筆記',
      view: '顯示方式',
      app: 'App',
      extension: '延伸功能',
    },
    nextPage: '下一頁',
    previousPage: '上一頁',
    scrollScreen: '按畫面捲動（捲動模式）',
    scrollLines: '按行捲動（捲動模式）',
  },
  keys: { esc: 'Esc', space: '空白鍵', pageUp: 'PgUp', pageDown: 'PgDn' },
  menus: {
    file: '檔案',
    edit: '編輯',
    view: '顯示方式',
    go: '前往',
    window: '視窗',
    about: (app: string) => `關於 ${app}`,
    services: '服務',
    hide: (app: string) => `隱藏 ${app}`,
    hideOthers: '隱藏其他',
    showAll: '顯示全部',
    quit: (app: string) => `結束 ${app}`,
    cut: '剪下',
    copy: '拷貝',
    paste: '貼上',
    selectAll: '全選',
    minimize: '縮到最小',
  },
  palette: {
    label: '指令面板',
    placeholder: '輸入指令、章節或設定',
    recentlyClosed: '最近關閉',
    reading: '閱讀',
    chapters: '章節',
    none: '沒有符合的指令',
    move: '移動',
    run: '執行',
    all: '所有快速鍵',
  },
  messages: {
    region: '訊息',
    dismiss: '關閉',
    saveFailed: '無法將筆記儲存到磁碟',
    retry: '重試',
    quitUnsaved: '部分筆記尚未儲存，因此 Linen 保持開啟',
    quitAnyway: '仍要結束',
  },
  commands: {
    'chapter.next': '下一章',
    'chapter.previous': '上一章',
    'search.open': '在書中搜尋',
    'search.next': '下一個結果',
    'search.previous': '上一個結果',
    'navigator.contents': '前往章節…',
    'goto.open': '前往位置…',
    'navigator.notes': '螢光標示與筆記',
    'selection.highlight': '螢光標示所選內容',
    'selection.note': '為所選內容加入筆記',
    'selection.focusBar': '移到選取動作',
    'reader.caretBrowsing': '游標瀏覽',
    'text.larger': '放大文字',
    'text.smaller': '縮小文字',
    'text.reset': '預設文字大小',
    'layout.pages': '翻頁模式',
    'layout.scroll': '捲動模式',
    'reader.settings': '閱讀設定…',
    'reader.simplifyStyles': '簡化這本書的樣式',
    'selection.lookUp': '查詢所選內容',
    'app.settings': '設定…',
    'palette.open': '指令面板',
    'shortcuts.show': '鍵盤快速鍵',
    'history.back': '返回',
    'library.show': '書庫',
    'book.open': '打開…',
    'window.fullScreen': '全螢幕',
    'edit.undo': '還原',
    'layer.close': '關閉圖層',
  },
}
