// The Simplified Chinese catalogue (L-1). A machine draft (2026-10-07, L-6): it
// follows docs/i18n/style.md and docs/i18n/glossary.md and waits for a native
// speaker's review in context before it ships. Keys, values and context: en.ts.

import { formatPercent } from './format'
import type { Messages } from './types'

const fileName = (path: string) => path.split('/').pop() ?? path

export const zhHans: Messages = {
  library: {
    emptyTitle: '你的书库是空的',
    emptyBody: '将 EPUB 文件拖到这里，或从电脑中打开一本。',
    openBook: '打开一本书…',
    open: '打开…',
    note: '图书会拷贝到你的书库，并保留在这台设备上。',
    title: '书库',
    count: (n: number) => `${n} 本书`,
    unknownAuthor: '未知作者',
    damaged: (n: number) => `${n} 本已损坏`,
    new: '新',
    finished: '已读完',
    percent: (fraction: number) => formatPercent(fraction),
    search: '搜索书库',
    searchPlaceholder: '搜索书名或作者',
    sortBy: (label: string) => `排序方式：${label}`,
    sorts: { recent: '最近', title: '书名', author: '作者' },
    view: '显示',
    viewGrid: '封面',
    viewList: '列表',
    neverOpened: '—',
    continueReading: '继续阅读',
    openedAt: (day: string, time: string) => `${day} ${time} 打开`,
    openedAgo: (ago: string) => `${ago}打开`,
    allBooks: '所有图书',
    resume: '继续阅读',
    itemMenu: (title: string) => `“${title}”的更多操作`,
    info: '图书信息',
    showFile: '在访达中显示',
    remove: '移除',
    removed: (title: string) => `已移除“${title}”`,
    restore: (title: string) => `恢复“${title}”`,
    noMatches: (q: string) => `没有与“${q}”匹配的图书`,
    damagedTitle: '这本书有一部分无法打开',
    damagedBody: (n: number, total: number) =>
      `${total ? `${total} 个章节中有 ${n} 个` : `${n} 个章节`}已损坏。你可以阅读其余部分；损坏的章节会在目录中标出，不会悄无声息地缺失。`,
    damagedFile: (title: string, size: string) => `${title} · ${size}`,
    readAnyway: '仍然阅读',
    showFileShort: '显示文件',
    clear: '清除',
    webkitTitle: '阅读图书需要更新版本的 Safari',
    webkitBody:
      'Linen 使用 Mac 自带的网页引擎来显示图书，它随 Safari 一起提供。这台 Mac 上的版本低于 Linen 所需的 Safari 16.4 或更高版本。请在“软件更新”中更新，然后再次打开这本书。你的书库和笔记都很安全。',
    webkitUpdate: '打开“软件更新”',
    webkitClose: '以后再说',
  },
  prefs: {
    title: '设置',
    sections: {
      general: '通用',
      reading: '阅读',
      library: '书库',
      dictionaries: '词典',
      extensions: '扩展',
      shortcuts: '快捷键',
      about: '关于',
    },
    theme: '主题',
    atLaunch: 'Linen 打开时',
    atLaunchLibrary: '显示书库',
    atLaunchBook: '重新打开上次的书',
    language: '语言',
    languageSystem: (name: string) => `系统（${name}）`,
    languageRestart: 'Linen 重新启动后会使用新语言。',
    restartNow: '立即重新启动',
    textSize: '文字大小',
    lineSpacing: '行距',
    font: '字体',
    pageWidth: '页面宽度',
    publisherStyles: '出版社样式',
    publisherFull: '完整',
    publisherBalanced: '平衡',
    publisherOff: '关闭',
    publisherHelp:
      '“平衡”保留图书的设计，但行距和对齐方式由你决定。“完整”保留全部样式；“关闭”显示纯文本。也可以从单本书的 ⋯ 菜单中简化它的样式。',
    crossfade: '翻页淡入淡出',
    crossfadeHelp: '翻页时页面在 120 毫秒内相互淡入，而不是立即切换。',
    announcements: '朗读翻页',
    announcementsHelp: '每次翻页后，屏幕阅读器会读出“第 N 页”。',
    folder: '书库文件夹',
    folderHelp:
      '你的图书、封面、高亮和笔记都在这个文件夹中。备份它即可保留这些内容；时间机器会自动备份。',
    showFolder: '在访达中显示',
    exportAll: '导出所有高亮和笔记…',
    exportHelp: '每本书一个 W3C Web Annotation 文件，其他应用也能读取。',
    exported: (n: number) => `已导出 ${n} 本书`,
    nothingToExport: '没有可导出的高亮。',
    uninstall: '从“应用程序”中移除 Linen 后，这个文件夹仍会保留。要同时移除书库，请将它一并删除。',
    extensionsIntro:
      '扩展会在固定的位置添加操作、面板、主题和导出器。它们不能改变页面的外观，未经你允许也不能读取你的图书或笔记。',
    extensionsNone: '扩展将在以后的版本中提供。',
    singleKeys: '单键快捷键',
    singleKeysHelp: '[ ] H N 等按键在文本获得焦点时可用。屏幕阅读器运行时会自动关闭。',
    showShortcuts: '显示所有快捷键',
    version: (v: string) => `版本 ${v}`,
    aboutLine: '一款安静的 EPUB 阅读器。你的图书保留在这台设备上。',
    fonts: 'Literata 和 OpenDyslexic 依据 SIL Open Font License 授权。',
    privacy:
      'Linen 不会向任何地方发送任何内容。如果出现问题，详细信息会写入这台 Mac 上的崩溃日志，你可以自行选择是否将其附加到邮件中。',
    showCrashLog: '显示崩溃日志',
  },
  extensions: {
    stopped: (name: string) => `${name} 已停止响应`,
    restart: '重新启动',
    notResponding: '未响应',
    restartNamed: (name: string) => `重新启动 ${name}`,
    manage: '管理扩展…',
    more: '扩展提供的更多操作',
    via: (name: string) => `来自扩展“${name}”`,
    exported: '已导出',
    exportFailed: (name: string) => `${name} 无法导出`,
  },
  extSettings: {
    install: '从文件安装…',
    builtin: '内置',
    themePack: '主题包',
    off: '关闭',
    canAccess: '可访问',
    adds: '添加',
    can: '可以',
    nothing: '无 — 主题不包含代码',
    noAccess: '仅限其自身的存储空间',
    enabled: (name: string) => `${name} 已开启`,
    failures: (n: number) => `最近停止响应 ${n} 次并已重新启动。阅读未受影响。`,
    suspended: '十分钟内三次停止响应，已暂停。阅读未受影响。',
    restart: '重新启动',
    disable: '停用',
    incompatible: (why: string) => `已关闭：${why}。`,
    remove: '移除…',
    pin: '在 ⋯ 菜单中显示其命令',
    restartWithout: '不带扩展重新启动',
    shiftHint: '也可以在 Linen 打开时按住 ⇧。',
    safeMode: 'Linen 已在不带扩展的情况下启动。下次打开时扩展会恢复。',
    installTitle: (name: string) => `要安装“${name}”吗？`,
    updateTitle: (name: string, version: string) => `“${name}” ${version} 需要更多权限`,
    notVerified: '未经 Linen 验证。请只安装你信任的人提供的扩展。',
    newAccess: '新的权限',
    cancel: '取消',
    installButton: '安装',
    update: '更新',
    keepCurrent: '保留当前版本',
    cantInstall: (name: string) => `无法安装“${name}”`,
    close: '关闭',
    installed: (name: string) => `已安装“${name}”`,
    removeTitle: (name: string) => `要移除“${name}”吗？`,
    removeBody: '同时删除它保存的内容吗？如果保留，重新安装该扩展时这些内容会回来。',
    keepData: '保留其数据',
    deleteData: '删除其数据',
    fileFilter: 'Linen 扩展',
    permissions: {
      'book.metadata': '查看图书的书名和作者',
      'book.selection': '读取你选中的文本',
      'book.text': '读取整本书',
      'annotations.read': '读取高亮和笔记',
      'annotations.write': '更改高亮和笔记',
      'library.read': '查看书库中的每一本书',
      'reading.sessions': '了解你何时阅读以及阅读多久',
      'files.import': '打开你选择的文件',
      'files.export': '保存到你选择的文件',
      background: '在后台运行',
    },
    connect: (host: string) => `连接到 ${host}`,
    connectAny: (suffix: string) => `连接到任何以 ${suffix} 结尾的地址`,
    commandsAdded: (n: number) => `${n} 个命令`,
    inSelectionMenu: (title: string) => `选择菜单中的“${title}”`,
    inLookupMenu: (title: string) => `查询窗口中的“${title}”`,
    navigatorTab: '导航栏标签',
    themesAdded: (n: number) => `${n} 个主题`,
    exportInNotes: '在笔记中导出',
  },
  info: {
    label: '图书信息',
    done: '完成',
    by: '作者',
    publisher: '出版社',
    published: '出版日期',
    language: '语言',
    identifier: '标识符',
    added: '添加日期',
    fileSize: '文件大小',
    layout: '版式',
    fixed: '固定版式',
    reflowable: '可重排',
    accessibility: '辅助功能',
    noAccessibility: '这本书未提供辅助功能信息。',
    description: '简介',
    sizeMB: (n: string) => `${n} MB`,
    sizeKB: (n: string) => `${n} KB`,
    a11y: {
      accessMode: {
        textual: '可作为文本阅读',
        visual: '包含视觉内容',
        auditory: '包含音频内容',
      },
      accessModeSufficient: {
        textual: '可完全作为文本阅读',
        visual: '部分内容需要视觉',
      },
      accessibilityFeature: {
        alternativeText: '图像有替代文本',
        longDescription: '复杂图像有详细描述',
        tableOfContents: '有目录',
        readingOrder: '有合理的阅读顺序',
        structuralNavigation: '有用于导航的标题',
        pageBreakMarkers: '标出纸书页码',
        printPageNumbers: '标出纸书页码',
        MathML: '以 MathML 呈现数学内容',
        displayTransformability: '文本样式可调整',
        synchronizedAudioText: '有朗读音频',
        ARIA: '使用 ARIA 角色',
        index: '有索引',
        captions: '有字幕',
      },
      accessibilityHazard: {
        none: '无已知危险',
        noFlashingHazard: '无闪烁危险',
        noMotionSimulationHazard: '无动态危险',
        noSoundHazard: '无声音危险',
        flashing: '警告：闪烁内容',
        motionSimulation: '警告：动态模拟',
        sound: '警告：声音',
        unknown: '危险未知',
      },
    },
  },
  update: {
    ready: (version: string) => `更新已就绪 · Linen ${version}`,
    restart: '重新启动',
    available: (version: string) => `Linen ${version} 现已推出`,
    download: '下载',
  },
  import: {
    addedDamaged: (title: string, n: number) => `已添加“${title}” · ${n} 个章节已损坏`,
    alreadyInLibrary: (path: string) => `“${fileName(path)}”已在你的书库中`,
    replaced: (title: string) => `已用较新的文件更新“${title}”`,
    drm: (path: string) => `“${fileName(path)}”受 DRM 保护，无法在 Linen 中打开`,
    hostile: (path: string) => `“${fileName(path)}”无法安全打开，未添加`,
    rejected: (path: string, reason: string) => `无法打开“${fileName(path)}” · ${reason}`,
    fileFilter: 'EPUB',
    reasons: {
      not_zip: '不是 zip 归档，或归档已截断',
      too_many_entries: (max: string) => `条目超过 ${max} 个`,
      too_large: '解压后大小超过 1 GB',
      compression_ratio: (entry: string, ratio: string) => `条目 ${entry} 的压缩比超过 ${ratio}:1`,
      unsafe_path: (entry: string) => `不安全的条目路径 ${entry}`,
      symlink: (entry: string) => `符号链接条目 ${entry}`,
      no_package: '没有 container.xml 或包文档',
      bad_package: '包文档不是格式正确的 XML',
      xml_entities: (entry: string) => `${entry} 声明了 XML 实体`,
      drm: (entry: string) => `${entry} 中有加密内容（DRM）`,
      no_chapters: '这本书的章节都无法打开',
    },
  },
  reader: {
    simplified: '已简化这本书的样式',
    unsimplified: '已恢复这本书自己的样式',
    undo: '撤销',
    library: '书库',
    more: '更多',
    caretOn: '光标浏览已开启。方向键移动光标；Shift 加方向键进行选择。',
    caretOff: '光标浏览已关闭',
    contents: '目录',
    previousPage: '上一页',
    nextPage: '下一页',
    minutesLeft: (n: number) => `本章还剩 ${n} 分钟`,
    resumedIn: (chapter: string) => `已从 ${chapter} 继续`,
    resumed: '已从上次的位置继续',
    goToBeginning: '前往开头',
    backToPage: (page: string) => `返回第 ${page} 页`,
    back: '返回',
    pageAnnouncement: (page: number) => `第 ${page} 页`,
    pageAnnouncementApprox: (page: number) => `约第 ${page} 页`,
    approxPage: (page: number) => `≈${page}`,
    fixedPages: (pages: number[], total: number) =>
      pages.length > 1
        ? `第 ${pages[0]}–${pages[pages.length - 1]} 页，共 ${total} 页`
        : `第 ${pages[0]} 页，共 ${total} 页`,
    zoomLevel: (zoom: number) => formatPercent(zoom),
    zoomFit: '适合',
    opening: (title: string) => `正在打开“${title}”…`,
  },
  search: {
    label: '在书中搜索',
    placeholder: '在书中搜索',
    clear: '清除搜索',
    count: (n: number, chapters: number) => `在 ${chapters} 个章节中找到 ${n} 个结果`,
    soFar: '（搜索中）',
    searching: (n: number, of: number) => `正在搜索第 ${n} 章，共 ${of} 章`,
    showAll: (n: number) => `显示全部 ${n} 个`,
    none: (q: string) => `没有“${q}”的结果`,
    options: '搜索选项',
    wholeWords: '全字匹配',
    regex: '正则表达式',
    invalid: '这个正则表达式无效。',
    next: '下一个',
    previous: '上一个',
    back: '返回你的页面',
    result: (i: number, n: number, chapter: string) =>
      [`第 ${i} 个结果，共 ${n} 个`, chapter].filter(Boolean).join(' · '),
  },
  navigator: {
    label: '导航栏',
    tabs: '导航栏部分',
    search: '搜索',
    notes: '笔记',
    more: '更多',
    close: '关闭导航栏',
    contents: '目录',
    loading: '正在读取目录…',
    generated: '根据标题生成',
    youAreHere: '你在这里',
    damaged: '已损坏',
  },
  aa: {
    label: '阅读设置',
    button: '阅读设置',
    textSize: '文字大小',
    sizeScope: (px: number) => `${px} px · 所有图书`,
    px: (px: number) => `${px} 像素`,
    theme: '主题',
    paper: '纸张',
    sepia: '棕褐',
    night: '夜间',
    auto: '自动',
    lineSpacing: '行距',
    compact: '紧凑',
    normal: '正常',
    loose: '宽松',
    layout: '版式',
    pages: '翻页',
    scroll: '滚动',
    allBooks: '所有图书',
    thisBook: '这本书',
    moreSettings: '更多设置…',
    anywhere: '⌘+ ⌘− 在任何地方都可用',
    codeHint: '这本书大部分是代码或表格。滚动模式可能更易阅读。',
    fixedLayout: '这本书是固定版式，文字大小和间距无法更改。按 ⌘+ 和 ⌘− 缩放页面。',
    font: '字体',
    fontBook: '图书',
    fontLiterata: 'Literata',
    fontSans: '无衬线',
    fontDyslexic: '读写障碍',
    fontDyslexicLong: 'OpenDyslexic',
    width: '页面宽度',
    narrow: '窄',
    wide: '宽',
  },
  annotations: {
    bar: '选择操作',
    barAnnounce: '选择操作，F6',
    highlightIn: (color: string, lastUsed: boolean) =>
      `用${color}高亮${lastUsed ? '，上次使用（H 或 ⇧⌘H）' : ''}`,
    colorOption: (color: string, current: boolean) => `${color}${current ? '，当前' : ''}`,
    note: '笔记',
    copy: '拷贝',
    search: '搜索',
    delete: '删除',
    copied: '已拷贝',
    highlighted: (color: string) => `已用${color}高亮`,
    deleted: '已删除高亮',
    noteDeleted: '已删除笔记',
    recolored: (color: string) => `高亮已改为${color}`,
    highlightCommand: (color: string) => `用${color}高亮`,
    undo: '撤销',
    restore: (quote: string) => `恢复高亮“${quote}”`,
    restoreNote: (quote: string) => `恢复“${quote}”上的笔记`,
    restoreColor: (quote: string) => `恢复“${quote}”的颜色`,
    noteTitle: (color: string) => `笔记 · ${color}`,
    noteLabel: '高亮上的笔记',
    noteText: '笔记文本',
    saving: '正在存储…',
    saved: '已存储',
    notSaved: '尚未存储',
    noteHint: '输入时自动存储 · 按 Esc 关闭，焦点回到文本',
    copyNote: '拷贝引文和笔记',
    deleteNote: '删除高亮和笔记',
    done: '完成',
    filter: '过滤高亮和笔记',
    all: '全部',
    only: (color: string) => `仅${color}`,
    counts: (h: number, n: number) => `${h} 个高亮 · ${n} 条笔记`,
    today: '今天',
    yesterday: '昨天',
    hasNote: '笔记',
    none: '还没有高亮。选中文本并选择一种颜色，或按 H。',
    noMatches: '没有匹配的高亮。',
    couldntPlace: '无法定位',
    changedReason: '保存之后图书文件发生了变化。',
    reattach: '重新附加',
    reattachPrompt: (quote: string) => `选择“${quote}”所在的段落`,
    attachHere: '附加到这里',
    cancel: '取消',
    reattached: '已重新附加高亮',
    unplacedAfterUpdate: (n: number) => `有 ${n} 个高亮无法在更新后的图书中定位`,
    show: '显示',
  },
  colors: { yellow: '黄色', green: '绿色', blue: '蓝色', rose: '玫瑰色' },
  colorsInText: { yellow: '黄色', green: '绿色', blue: '蓝色', rose: '玫瑰色' },
  goto: {
    label: '前往位置',
    percent: '百分比',
    chapter: '章节',
    page: '纸书页码',
    percentLabel: '图书的百分比',
    chapterLabel: '章节',
    pageLabel: '纸书页码',
    go: '前往',
    stays: '你当前的位置会保留在返回记录中（⌘[）。',
    percentIn: (pct: number) => `${formatPercent(pct / 100)} 位于 `,
    pageIn: (page: string) => `第 ${page} 页位于 `,
    chapterAt: (pct: number) => ` 从 ${formatPercent(pct / 100)} 开始。`,
    sentenceEnd: '。',
    noPage: (page: string) => `这本书中没有第 ${page} 页。`,
    pageListOnly: '只有在图书包含页码列表时才能使用纸书页码。',
    open: '前往…',
    scrubber: '在书中的位置',
  },
  peek: {
    label: (n: string) => `注释 ${n}`,
    title: (n: string) => `注释 ${n}`,
    hint: '按 Esc 关闭 · 焦点回到标记',
    openInPlace: '在原位置打开注释',
    copy: '拷贝',
    copied: '已拷贝注释',
    missing: '在书中找不到这条注释。',
  },
  shortcuts: {
    intro:
      '可以为任何命令设置快捷键，包括扩展提供的命令。快捷键需要使用 ⌘、⌃ 或 ⌥（功能键可单独使用）；扩展不能占用 Linen 自己的快捷键。',
    none: '无',
    change: '更改',
    cancel: '取消',
    remove: '移除',
    reset: '复位',
    resetAll: '复位所有快捷键',
    typeNow: '键入快捷键…',
    changeFor: (title: string) => `更改“${title}”的快捷键`,
    removeFor: (title: string) => `移除“${title}”的快捷键`,
    resetFor: (title: string) => `复位“${title}”的快捷键`,
    needsModifier: '快捷键需要使用 ⌘、⌃ 或 ⌥（功能键可单独使用）。',
    reserved: (keys: string) => `${keys} 属于 macOS 或 Linen，无法更改。`,
    taken: (keys: string, title: string) =>
      `${keys} 是 Linen 用于“${title}”的快捷键；扩展不能占用它。`,
    moved: (keys: string, title: string) => `${keys} 不再执行“${title}”。`,
  },
  lookUp: {
    action: '查询',
    label: (word: string) => `“${word}”的释义`,
    title: '词典',
    hint: '按 Esc 关闭',
    looking: '正在查询…',
    none: (word: string) => `这台 Mac 上没有词典收录“${word}”。`,
    openDictionary: '在词典中打开',
    searchBook: '在书中搜索',
    contextMenu: (word: string) => `查询“${word.length > 24 ? word.slice(0, 23) + '…' : word}”`,
  },
  // Reading Lens（PROVISIONAL，机器草稿，待审）
  lens: {
    macDictionaries: '这台 Mac 上的词典',
    labelMacDictionary: '词典 · 在这台 Mac 上',
    labelAi: (model: string) => `AI 解释 · ${model}`,
    labelDictionary: (name: string) => `词典 · ${name}`,
    explanationOf: (word: string) => `“${word}”的解释`,
    lookUpWord: (word: string) => `查询“${word}”`,
    lookUpWith: '查询方式',
    lookUpWithCommand: (title: string) => `用${title}查询`,
    asking: (name: string) => `正在询问 ${name}…`,
    copyExplanation: '拷贝解释',
    copied: '已拷贝解释',
    more: '更多',
    less: '收起',
    whatWasSent: '发送了什么',
    sentBy: (name: string) => `由 ${name} 发送`,
    back: '返回',
    searchInBook: '在书中搜索',
    offline: '你已离线。',
    offlineDetail: (name: string) => `${name} 需要网络连接。`,
    timeout: (name: string) => `${name} 未在 10 秒内回答。`,
    unauthorized: (name: string) => `${name} 未接受密钥。`,
    unauthorizedDetail: '密钥可能已过期或被撤销。',
    rateLimited: (name: string) => `${name} 正在限制请求。`,
    rateLimitedDetail: '请一分钟后再试。',
    unavailable: (name: string) => `${name} 目前不可用。`,
    badAnswer: (name: string) => `${name} 发来的回答无法显示。`,
    stopped: (name: string) => `${name} 停止响应。`,
    stoppedDetail: '阅读未受影响。',
    continue: '继续',
    notNow: '以后再说',
    audioUnavailable: '无法播放音频',
    explainInContext: '结合上下文解释',
    noEntry: (word: string) => `你的词典中没有“${word}”的词条。`,
    dictionaryFrame: (title: string) => `“${title}”中的词条`,
    tryAgain: '重试',
    restart: (name: string) => `重新启动 ${name}`,
  },
  // Reading Lens（PROVISIONAL，机器草稿，待审）
  dictSettings: {
    intro:
      '你添加的词典会拷贝到资料库中并留在这台 Mac 上。查询单词时 Linen 会显示其中的词条，绝不会把它们发送到任何地方。',
    add: '添加词典…',
    order: '顺序决定查询窗口首先显示哪本词典。',
    fileFilter: '词典',
    details: (entries: string, mdd: boolean) =>
      mdd ? `MDX 和 MDD · ${entries} 个词条` : `MDX · ${entries} 个词条`,
    on: '开启',
    remove: '移除',
    removeNamed: (title: string) => `移除“${title}”`,
    moveUp: (title: string) => `上移“${title}”`,
    moveDown: (title: string) => `下移“${title}”`,
    importing: '正在导入… 导入完成前仍使用之前的版本。',
    importingNamed: (name: string) => `正在导入“${name}”`,
    cancel: '取消',
    dismiss: '关闭',
    added: (title: string) => `已添加“${title}”。`,
    alreadyInstalled: (title: string) => `这本词典已作为“${title}”安装。`,
    registered: '这本词典受注册保护，只能在其来源的应用中使用，因此 Linen 无法打开。',
    lzo: '这本词典使用 LZO 压缩，Linen 无法读取。',
    encoding: (name: string) => `这本词典的文字使用 ${name} 编码，Linen 无法读取。`,
    damaged: '这本词典已损坏，Linen 无法打开。',
    tooLarge: '这本词典的某部分超出了 Linen 允许的大小。',
    changed: '添加过程中文件发生了变化。请重试。',
    notMdx: '这不是 MDX 词典。',
    failed: '无法添加这本词典。仍在使用之前的版本。',
    none: '还没有词典。',
  },
  image: {
    label: '图像',
    close: '关闭图像',
    zoomIn: '放大',
    zoomOut: '缩小',
    fit: '适合',
  },
  cheatSheet: {
    title: '键盘快捷键',
    close: '关闭',
    singleKeys: '单键快捷键（例如 [ 和 ]）在书中文本获得焦点且没有运行屏幕阅读器时可用。',
    pages: '翻页',
    sections: {
      navigation: '导航',
      reading: '阅读',
      search: '搜索',
      annotation: '高亮和笔记',
      view: '显示',
      app: '应用',
      extension: '扩展',
    },
    nextPage: '下一页',
    previousPage: '上一页',
    scrollScreen: '按屏滚动（滚动模式）',
    scrollLines: '按行滚动（滚动模式）',
  },
  keys: { esc: 'Esc', space: '空格', pageUp: 'PgUp', pageDown: 'PgDn' },
  menus: {
    file: '文件',
    edit: '编辑',
    view: '显示',
    go: '前往',
    window: '窗口',
    about: (app: string) => `关于 ${app}`,
    services: '服务',
    hide: (app: string) => `隐藏 ${app}`,
    hideOthers: '隐藏其他',
    showAll: '全部显示',
    quit: (app: string) => `退出 ${app}`,
    cut: '剪切',
    copy: '拷贝',
    paste: '粘贴',
    selectAll: '全选',
    minimize: '最小化',
  },
  palette: {
    label: '命令面板',
    placeholder: '键入命令、章节或设置',
    recentlyClosed: '最近关闭',
    reading: '阅读',
    chapters: '章节',
    none: '没有匹配的命令',
    move: '移动',
    run: '执行',
    all: '所有快捷键',
  },
  messages: {
    region: '消息',
    dismiss: '关闭',
    saveFailed: '无法将笔记存储到磁盘',
    retry: '重试',
    quitUnsaved: '部分笔记尚未存储，因此 Linen 保持打开',
    quitAnyway: '仍然退出',
  },
  commands: {
    'chapter.next': '下一章',
    'chapter.previous': '上一章',
    'search.open': '在书中搜索',
    'search.next': '下一个结果',
    'search.previous': '上一个结果',
    'navigator.contents': '前往章节…',
    'goto.open': '前往位置…',
    'navigator.notes': '高亮和笔记',
    'selection.highlight': '高亮所选内容',
    'selection.note': '为所选内容添加笔记',
    'selection.focusBar': '移到选择操作',
    'reader.caretBrowsing': '光标浏览',
    'text.larger': '放大文字',
    'text.smaller': '缩小文字',
    'text.reset': '默认文字大小',
    'layout.pages': '翻页模式',
    'layout.scroll': '滚动模式',
    'reader.settings': '阅读设置…',
    'reader.simplifyStyles': '简化这本书的样式',
    'selection.lookUp': '查询所选内容',
    'app.settings': '设置…',
    'palette.open': '命令面板',
    'shortcuts.show': '键盘快捷键',
    'history.back': '返回',
    'library.show': '书库',
    'book.open': '打开…',
    'window.fullScreen': '全屏幕',
    'edit.undo': '撤销',
    'layer.close': '关闭图层',
  },
}
